// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (org_id, category_id, name, description, is_active, sort_order)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, org_id, category_id, name, description, image_url, is_active, sort_order, created_at, updated_at
`

type CreateProductParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	CategoryID  pgtype.UUID `json:"category_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	SortOrder   int32       `json:"sort_order"`
}

type CreateProductRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsActive    bool               `json:"is_active"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OrgID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.SortOrder,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductImagesByProduct = `-- name: DeleteProductImagesByProduct :exec
DELETE FROM product_images WHERE product_id = $1
`

func (q *Queries) DeleteProductImagesByProduct(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImagesByProduct, productID)
	return err
}

const deleteProductOptionsByProduct = `-- name: DeleteProductOptionsByProduct :exec
DELETE FROM product_options WHERE product_id = $1
`

func (q *Queries) DeleteProductOptionsByProduct(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductOptionsByProduct, productID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, org_id, category_id, name, description, image_url, is_active, sort_order, created_at, updated_at
FROM products
WHERE id = $1 AND deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsActive    bool               `json:"is_active"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT id, org_id, category_id, name, description, image_url, is_active, sort_order, created_at, updated_at
FROM products
WHERE name = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetProductByNameRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsActive    bool               `json:"is_active"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProductByName(ctx context.Context, name string) (GetProductByNameRow, error) {
	row := q.db.QueryRow(ctx, getProductByName, name)
	var i GetProductByNameRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductImage = `-- name: InsertProductImage :one
INSERT INTO product_images (org_id, product_id, variant_id, url, sort_order)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, product_id, variant_id, url, sort_order, created_at, updated_at
`

type InsertProductImageParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ProductID pgtype.UUID `json:"product_id"`
	VariantID pgtype.UUID `json:"variant_id"`
	Url       string      `json:"url"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProductImage(ctx context.Context, arg InsertProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, insertProductImage,
		arg.OrgID,
		arg.ProductID,
		arg.VariantID,
		arg.Url,
		arg.SortOrder,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProductID,
		&i.VariantID,
		&i.Url,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductOption = `-- name: InsertProductOption :one
INSERT INTO product_options (org_id, product_id, name, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, product_id, name, sort_order, created_at, updated_at
`

type InsertProductOptionParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ProductID pgtype.UUID `json:"product_id"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProductOption(ctx context.Context, arg InsertProductOptionParams) (ProductOption, error) {
	row := q.db.QueryRow(ctx, insertProductOption,
		arg.OrgID,
		arg.ProductID,
		arg.Name,
		arg.SortOrder,
	)
	var i ProductOption
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProductID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductOptionValue = `-- name: InsertProductOptionValue :one
INSERT INTO product_option_values (org_id, option_id, value, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, option_id, value, sort_order, created_at, updated_at
`

type InsertProductOptionValueParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	OptionID  pgtype.UUID `json:"option_id"`
	Value     string      `json:"value"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) InsertProductOptionValue(ctx context.Context, arg InsertProductOptionValueParams) (ProductOptionValue, error) {
	row := q.db.QueryRow(ctx, insertProductOptionValue,
		arg.OrgID,
		arg.OptionID,
		arg.Value,
		arg.SortOrder,
	)
	var i ProductOptionValue
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OptionID,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductVariant = `-- name: InsertProductVariant :one
INSERT INTO product_variants (org_id, product_id, name, sku, barcode, price, cost_price,
                              track_stock, is_active, sort_order)
VALUES ($1, $2, $3,
        $4, $5,
        $6, $7,
        $8, $9, $10)
RETURNING id, org_id, product_id, name, sku, barcode, price, cost_price,
          track_stock, is_active, sort_order, created_at, updated_at
`

type InsertProductVariantParams struct {
	OrgID      pgtype.UUID    `json:"org_id"`
	ProductID  pgtype.UUID    `json:"product_id"`
	Name       string         `json:"name"`
	Sku        pgtype.Text    `json:"sku"`
	Barcode    pgtype.Text    `json:"barcode"`
	Price      pgtype.Numeric `json:"price"`
	CostPrice  pgtype.Numeric `json:"cost_price"`
	TrackStock bool           `json:"track_stock"`
	IsActive   bool           `json:"is_active"`
	SortOrder  int32          `json:"sort_order"`
}

type InsertProductVariantRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	Name       string             `json:"name"`
	Sku        pgtype.Text        `json:"sku"`
	Barcode    pgtype.Text        `json:"barcode"`
	Price      pgtype.Numeric     `json:"price"`
	CostPrice  pgtype.Numeric     `json:"cost_price"`
	TrackStock bool               `json:"track_stock"`
	IsActive   bool               `json:"is_active"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertProductVariant(ctx context.Context, arg InsertProductVariantParams) (InsertProductVariantRow, error) {
	row := q.db.QueryRow(ctx, insertProductVariant,
		arg.OrgID,
		arg.ProductID,
		arg.Name,
		arg.Sku,
		arg.Barcode,
		arg.Price,
		arg.CostPrice,
		arg.TrackStock,
		arg.IsActive,
		arg.SortOrder,
	)
	var i InsertProductVariantRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProductID,
		&i.Name,
		&i.Sku,
		&i.Barcode,
		&i.Price,
		&i.CostPrice,
		&i.TrackStock,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProductVariantOptionValue = `-- name: InsertProductVariantOptionValue :exec
INSERT INTO product_variant_option_values (org_id, variant_id, option_value_id)
VALUES ($1, $2, $3)
`

type InsertProductVariantOptionValueParams struct {
	OrgID         pgtype.UUID `json:"org_id"`
	VariantID     pgtype.UUID `json:"variant_id"`
	OptionValueID pgtype.UUID `json:"option_value_id"`
}

func (q *Queries) InsertProductVariantOptionValue(ctx context.Context, arg InsertProductVariantOptionValueParams) error {
	_, err := q.db.Exec(ctx, insertProductVariantOptionValue, arg.OrgID, arg.VariantID, arg.OptionValueID)
	return err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, org_id, product_id, variant_id, url, sort_order, created_at, updated_at
FROM product_images
WHERE product_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID pgtype.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProductID,
			&i.VariantID,
			&i.Url,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductOptionValues = `-- name: ListProductOptionValues :many
SELECT pov.id, pov.org_id, pov.option_id, pov.value, pov.sort_order, pov.created_at, pov.updated_at
FROM product_option_values pov
JOIN product_options po ON po.id = pov.option_id
WHERE po.product_id = $1
ORDER BY pov.option_id, pov.sort_order ASC
`

func (q *Queries) ListProductOptionValues(ctx context.Context, productID pgtype.UUID) ([]ProductOptionValue, error) {
	rows, err := q.db.Query(ctx, listProductOptionValues, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOptionValue{}
	for rows.Next() {
		var i ProductOptionValue
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OptionID,
			&i.Value,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductOptions = `-- name: ListProductOptions :many
SELECT id, org_id, product_id, name, sort_order, created_at, updated_at
FROM product_options
WHERE product_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListProductOptions(ctx context.Context, productID pgtype.UUID) ([]ProductOption, error) {
	rows, err := q.db.Query(ctx, listProductOptions, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductOption{}
	for rows.Next() {
		var i ProductOption
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProductID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariantOptionValues = `-- name: ListProductVariantOptionValues :many
SELECT pvov.variant_id, pvov.option_value_id
FROM product_variant_option_values pvov
JOIN product_variants pv ON pv.id = pvov.variant_id
WHERE pv.product_id = $1 AND pv.deleted_at IS NULL
`

type ListProductVariantOptionValuesRow struct {
	VariantID     pgtype.UUID `json:"variant_id"`
	OptionValueID pgtype.UUID `json:"option_value_id"`
}

func (q *Queries) ListProductVariantOptionValues(ctx context.Context, productID pgtype.UUID) ([]ListProductVariantOptionValuesRow, error) {
	rows, err := q.db.Query(ctx, listProductVariantOptionValues, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductVariantOptionValuesRow{}
	for rows.Next() {
		var i ListProductVariantOptionValuesRow
		if err := rows.Scan(&i.VariantID, &i.OptionValueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT id, org_id, product_id, name, sku, barcode, price, cost_price,
       track_stock, is_active, sort_order, created_at, updated_at
FROM product_variants
WHERE product_id = $1 AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListProductVariantsRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	Name       string             `json:"name"`
	Sku        pgtype.Text        `json:"sku"`
	Barcode    pgtype.Text        `json:"barcode"`
	Price      pgtype.Numeric     `json:"price"`
	CostPrice  pgtype.Numeric     `json:"cost_price"`
	TrackStock bool               `json:"track_stock"`
	IsActive   bool               `json:"is_active"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProductVariants(ctx context.Context, productID pgtype.UUID) ([]ListProductVariantsRow, error) {
	rows, err := q.db.Query(ctx, listProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductVariantsRow{}
	for rows.Next() {
		var i ListProductVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProductID,
			&i.Name,
			&i.Sku,
			&i.Barcode,
			&i.Price,
			&i.CostPrice,
			&i.TrackStock,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const softDeleteProductVariantsByProduct = `-- name: SoftDeleteProductVariantsByProduct :exec
UPDATE product_variants
SET deleted_at = now(), updated_at = now()
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProductVariantsByProduct(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProductVariantsByProduct, productID)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name        = $1,
    description = $2,
    category_id = $3,
    is_active   = $4,
    sort_order  = $5,
    updated_at  = now()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, org_id, category_id, name, description, image_url, is_active, sort_order, created_at, updated_at
`

type UpdateProductParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CategoryID  pgtype.UUID `json:"category_id"`
	IsActive    bool        `json:"is_active"`
	SortOrder   int32       `json:"sort_order"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateProductRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsActive    bool               `json:"is_active"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
