// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (org_id, parent_id, name, sort_order, color)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, parent_id, name, sort_order, color, image_url, created_at, updated_at
`

type CreateCategoryParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	Color     pgtype.Text `json:"color"`
}

type CreateCategoryRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	Color     pgtype.Text        `json:"color"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.OrgID,
		arg.ParentID,
		arg.Name,
		arg.SortOrder,
		arg.Color,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.Color,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, org_id, parent_id, name, sort_order, color, image_url, created_at, updated_at
FROM categories
WHERE id = $1 AND deleted_at IS NULL
`

type GetCategoryByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	Color     pgtype.Text        `json:"color"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.Color,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, org_id, parent_id, name, sort_order, color, image_url, created_at, updated_at
FROM categories
WHERE name = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetCategoryByNameRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	Color     pgtype.Text        `json:"color"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (GetCategoryByNameRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, name)
	var i GetCategoryByNameRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.Color,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, org_id, parent_id, name, sort_order, color, image_url, created_at, updated_at
FROM categories
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

type ListCategoriesRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	Color     pgtype.Text        `json:"color"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.SortOrder,
			&i.Color,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name       = $1,
    parent_id  = $2,
    color      = $3,
    sort_order = $4,
    updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, org_id, parent_id, name, sort_order, color, image_url, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name      string      `json:"name"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Color     pgtype.Text `json:"color"`
	SortOrder int32       `json:"sort_order"`
	ID        pgtype.UUID `json:"id"`
}

type UpdateCategoryRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	Color     pgtype.Text        `json:"color"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.ParentID,
		arg.Color,
		arg.SortOrder,
		arg.ID,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.Color,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
