// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    org_id, name, email, phone, notes,
    code, address, company, tax_code, date_of_birth, gender, facebook, is_active
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10,
    $11, $12, $13
)
RETURNING id, org_id, name, email, phone, notes,
          code, address, company, tax_code, date_of_birth, gender, facebook, is_active,
          created_at, updated_at
`

type CreateCustomerParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	Notes       pgtype.Text `json:"notes"`
	Code        pgtype.Text `json:"code"`
	Address     pgtype.Text `json:"address"`
	Company     pgtype.Text `json:"company"`
	TaxCode     pgtype.Text `json:"tax_code"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Gender      pgtype.Text `json:"gender"`
	Facebook    pgtype.Text `json:"facebook"`
	IsActive    bool        `json:"is_active"`
}

type CreateCustomerRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Notes       pgtype.Text        `json:"notes"`
	Code        pgtype.Text        `json:"code"`
	Address     pgtype.Text        `json:"address"`
	Company     pgtype.Text        `json:"company"`
	TaxCode     pgtype.Text        `json:"tax_code"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Gender      pgtype.Text        `json:"gender"`
	Facebook    pgtype.Text        `json:"facebook"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.OrgID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Notes,
		arg.Code,
		arg.Address,
		arg.Company,
		arg.TaxCode,
		arg.DateOfBirth,
		arg.Gender,
		arg.Facebook,
		arg.IsActive,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.Code,
		&i.Address,
		&i.Company,
		&i.TaxCode,
		&i.DateOfBirth,
		&i.Gender,
		&i.Facebook,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomerGroupMembersByCustomer = `-- name: DeleteCustomerGroupMembersByCustomer :exec
DELETE FROM customer_group_members
WHERE customer_id = $1
`

func (q *Queries) DeleteCustomerGroupMembersByCustomer(ctx context.Context, customerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomerGroupMembersByCustomer, customerID)
	return err
}

const getCustomerByCode = `-- name: GetCustomerByCode :one
SELECT id, org_id, name, email, phone, notes,
       code, address, company, tax_code, date_of_birth, gender, facebook, is_active,
       created_at, updated_at
FROM customers
WHERE org_id = $1 AND code = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerByCodeParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Code  pgtype.Text `json:"code"`
}

type GetCustomerByCodeRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Notes       pgtype.Text        `json:"notes"`
	Code        pgtype.Text        `json:"code"`
	Address     pgtype.Text        `json:"address"`
	Company     pgtype.Text        `json:"company"`
	TaxCode     pgtype.Text        `json:"tax_code"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Gender      pgtype.Text        `json:"gender"`
	Facebook    pgtype.Text        `json:"facebook"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerByCode(ctx context.Context, arg GetCustomerByCodeParams) (GetCustomerByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByCode, arg.OrgID, arg.Code)
	var i GetCustomerByCodeRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.Code,
		&i.Address,
		&i.Company,
		&i.TaxCode,
		&i.DateOfBirth,
		&i.Gender,
		&i.Facebook,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, org_id, name, email, phone, notes,
       code, address, company, tax_code, date_of_birth, gender, facebook, is_active,
       created_at, updated_at
FROM customers
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerByEmailRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Notes       pgtype.Text        `json:"notes"`
	Code        pgtype.Text        `json:"code"`
	Address     pgtype.Text        `json:"address"`
	Company     pgtype.Text        `json:"company"`
	TaxCode     pgtype.Text        `json:"tax_code"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Gender      pgtype.Text        `json:"gender"`
	Facebook    pgtype.Text        `json:"facebook"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerByEmail(ctx context.Context, email pgtype.Text) (GetCustomerByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i GetCustomerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.Code,
		&i.Address,
		&i.Company,
		&i.TaxCode,
		&i.DateOfBirth,
		&i.Gender,
		&i.Facebook,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, org_id, name, email, phone, notes,
       code, address, company, tax_code, date_of_birth, gender, facebook, is_active,
       created_at, updated_at
FROM customers
WHERE id = $1 AND deleted_at IS NULL
`

type GetCustomerByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Notes       pgtype.Text        `json:"notes"`
	Code        pgtype.Text        `json:"code"`
	Address     pgtype.Text        `json:"address"`
	Company     pgtype.Text        `json:"company"`
	TaxCode     pgtype.Text        `json:"tax_code"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Gender      pgtype.Text        `json:"gender"`
	Facebook    pgtype.Text        `json:"facebook"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (GetCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.Code,
		&i.Address,
		&i.Company,
		&i.TaxCode,
		&i.DateOfBirth,
		&i.Gender,
		&i.Facebook,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, org_id, name, email, phone, notes,
       code, address, company, tax_code, date_of_birth, gender, facebook, is_active,
       created_at, updated_at
FROM customers
WHERE phone = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerByPhoneRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Notes       pgtype.Text        `json:"notes"`
	Code        pgtype.Text        `json:"code"`
	Address     pgtype.Text        `json:"address"`
	Company     pgtype.Text        `json:"company"`
	TaxCode     pgtype.Text        `json:"tax_code"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Gender      pgtype.Text        `json:"gender"`
	Facebook    pgtype.Text        `json:"facebook"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone pgtype.Text) (GetCustomerByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i GetCustomerByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.Code,
		&i.Address,
		&i.Company,
		&i.TaxCode,
		&i.DateOfBirth,
		&i.Gender,
		&i.Facebook,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomerGroupMember = `-- name: InsertCustomerGroupMember :exec
INSERT INTO customer_group_members (org_id, group_id, customer_id)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, customer_id) DO NOTHING
`

type InsertCustomerGroupMemberParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	GroupID    pgtype.UUID `json:"group_id"`
	CustomerID pgtype.UUID `json:"customer_id"`
}

func (q *Queries) InsertCustomerGroupMember(ctx context.Context, arg InsertCustomerGroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertCustomerGroupMember, arg.OrgID, arg.GroupID, arg.CustomerID)
	return err
}

const listCustomerGroupMembersByCustomer = `-- name: ListCustomerGroupMembersByCustomer :many
SELECT id, org_id, group_id, customer_id, created_at
FROM customer_group_members
WHERE customer_id = $1
`

func (q *Queries) ListCustomerGroupMembersByCustomer(ctx context.Context, customerID pgtype.UUID) ([]CustomerGroupMember, error) {
	rows, err := q.db.Query(ctx, listCustomerGroupMembersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerGroupMember{}
	for rows.Next() {
		var i CustomerGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GroupID,
			&i.CustomerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSummaries = `-- name: ListCustomerSummaries :many
SELECT c.id,
       c.name,
       c.email,
       c.phone,
       c.code,
       c.company,
       c.is_active,
       COALESCE(STRING_AGG(g.name, ', ' ORDER BY g.name), '') AS group_names
FROM customers c
LEFT JOIN customer_group_members m
       ON m.customer_id = c.id
LEFT JOIN customer_groups g
       ON g.id = m.group_id AND g.deleted_at IS NULL
WHERE c.deleted_at IS NULL
GROUP BY c.id, c.name, c.email, c.phone, c.code, c.company, c.is_active, c.created_at
ORDER BY c.name ASC
`

type ListCustomerSummariesRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Email      pgtype.Text `json:"email"`
	Phone      pgtype.Text `json:"phone"`
	Code       pgtype.Text `json:"code"`
	Company    pgtype.Text `json:"company"`
	IsActive   bool        `json:"is_active"`
	GroupNames interface{} `json:"group_names"`
}

func (q *Queries) ListCustomerSummaries(ctx context.Context) ([]ListCustomerSummariesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerSummariesRow{}
	for rows.Next() {
		var i ListCustomerSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Code,
			&i.Company,
			&i.IsActive,
			&i.GroupNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customers
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCustomer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, id)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name          = $1,
    email         = $2,
    phone         = $3,
    notes         = $4,
    code          = $5,
    address       = $6,
    company       = $7,
    tax_code      = $8,
    date_of_birth = $9,
    gender        = $10,
    facebook      = $11,
    is_active     = $12,
    updated_at    = now()
WHERE id = $13 AND deleted_at IS NULL
RETURNING id, org_id, name, email, phone, notes,
          code, address, company, tax_code, date_of_birth, gender, facebook, is_active,
          created_at, updated_at
`

type UpdateCustomerParams struct {
	Name        string      `json:"name"`
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	Notes       pgtype.Text `json:"notes"`
	Code        pgtype.Text `json:"code"`
	Address     pgtype.Text `json:"address"`
	Company     pgtype.Text `json:"company"`
	TaxCode     pgtype.Text `json:"tax_code"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Gender      pgtype.Text `json:"gender"`
	Facebook    pgtype.Text `json:"facebook"`
	IsActive    bool        `json:"is_active"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateCustomerRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Notes       pgtype.Text        `json:"notes"`
	Code        pgtype.Text        `json:"code"`
	Address     pgtype.Text        `json:"address"`
	Company     pgtype.Text        `json:"company"`
	TaxCode     pgtype.Text        `json:"tax_code"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Gender      pgtype.Text        `json:"gender"`
	Facebook    pgtype.Text        `json:"facebook"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (UpdateCustomerRow, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Notes,
		arg.Code,
		arg.Address,
		arg.Company,
		arg.TaxCode,
		arg.DateOfBirth,
		arg.Gender,
		arg.Facebook,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.Code,
		&i.Address,
		&i.Company,
		&i.TaxCode,
		&i.DateOfBirth,
		&i.Gender,
		&i.Facebook,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
