// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (org_id, name, email, phone, notes)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, name, email, phone, notes, created_at, updated_at
`

type CreateCustomerParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
	Email pgtype.Text `json:"email"`
	Phone pgtype.Text `json:"phone"`
	Notes pgtype.Text `json:"notes"`
}

type CreateCustomerRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.OrgID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Notes,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomerGroupMembersByCustomer = `-- name: DeleteCustomerGroupMembersByCustomer :exec
DELETE FROM customer_group_members
WHERE customer_id = $1
`

func (q *Queries) DeleteCustomerGroupMembersByCustomer(ctx context.Context, customerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomerGroupMembersByCustomer, customerID)
	return err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, org_id, name, email, phone, notes, created_at, updated_at
FROM customers
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerByEmailRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerByEmail(ctx context.Context, email pgtype.Text) (GetCustomerByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i GetCustomerByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, org_id, name, email, phone, notes, created_at, updated_at
FROM customers
WHERE id = $1 AND deleted_at IS NULL
`

type GetCustomerByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (GetCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, org_id, name, email, phone, notes, created_at, updated_at
FROM customers
WHERE phone = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerByPhoneRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone pgtype.Text) (GetCustomerByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, phone)
	var i GetCustomerByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCustomerGroupMember = `-- name: InsertCustomerGroupMember :exec
INSERT INTO customer_group_members (org_id, group_id, customer_id)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, customer_id) DO NOTHING
`

type InsertCustomerGroupMemberParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	GroupID    pgtype.UUID `json:"group_id"`
	CustomerID pgtype.UUID `json:"customer_id"`
}

func (q *Queries) InsertCustomerGroupMember(ctx context.Context, arg InsertCustomerGroupMemberParams) error {
	_, err := q.db.Exec(ctx, insertCustomerGroupMember, arg.OrgID, arg.GroupID, arg.CustomerID)
	return err
}

const listCustomerGroupMembersByCustomer = `-- name: ListCustomerGroupMembersByCustomer :many
SELECT id, org_id, group_id, customer_id, created_at
FROM customer_group_members
WHERE customer_id = $1
`

func (q *Queries) ListCustomerGroupMembersByCustomer(ctx context.Context, customerID pgtype.UUID) ([]CustomerGroupMember, error) {
	rows, err := q.db.Query(ctx, listCustomerGroupMembersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerGroupMember{}
	for rows.Next() {
		var i CustomerGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GroupID,
			&i.CustomerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerSummaries = `-- name: ListCustomerSummaries :many
SELECT c.id,
       c.name,
       c.email,
       c.phone,
       COALESCE(STRING_AGG(g.name, ', ' ORDER BY g.name), '') AS group_names
FROM customers c
LEFT JOIN customer_group_members m
       ON m.customer_id = c.id
LEFT JOIN customer_groups g
       ON g.id = m.group_id AND g.deleted_at IS NULL
WHERE c.deleted_at IS NULL
GROUP BY c.id, c.name, c.email, c.phone, c.created_at
ORDER BY c.name ASC
`

type ListCustomerSummariesRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Email      pgtype.Text `json:"email"`
	Phone      pgtype.Text `json:"phone"`
	GroupNames interface{} `json:"group_names"`
}

func (q *Queries) ListCustomerSummaries(ctx context.Context) ([]ListCustomerSummariesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerSummariesRow{}
	for rows.Next() {
		var i ListCustomerSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.GroupNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customers
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCustomer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, id)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name       = $1,
    email      = $2,
    phone      = $3,
    notes      = $4,
    updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, org_id, name, email, phone, notes, created_at, updated_at
`

type UpdateCustomerParams struct {
	Name  string      `json:"name"`
	Email pgtype.Text `json:"email"`
	Phone pgtype.Text `json:"phone"`
	Notes pgtype.Text `json:"notes"`
	ID    pgtype.UUID `json:"id"`
}

type UpdateCustomerRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (UpdateCustomerRow, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Notes,
		arg.ID,
	)
	var i UpdateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
