// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_group.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerGroup = `-- name: CreateCustomerGroup :one
INSERT INTO customer_groups (org_id, name, description, discount_type, discount_value)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, name, description, discount_type, discount_value, created_at, updated_at
`

type CreateCustomerGroupParams struct {
	OrgID         pgtype.UUID    `json:"org_id"`
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	DiscountType  pgtype.Text    `json:"discount_type"`
	DiscountValue pgtype.Numeric `json:"discount_value"`
}

type CreateCustomerGroupRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	DiscountType  pgtype.Text        `json:"discount_type"`
	DiscountValue pgtype.Numeric     `json:"discount_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomerGroup(ctx context.Context, arg CreateCustomerGroupParams) (CreateCustomerGroupRow, error) {
	row := q.db.QueryRow(ctx, createCustomerGroup,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.DiscountType,
		arg.DiscountValue,
	)
	var i CreateCustomerGroupRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerGroupByID = `-- name: GetCustomerGroupByID :one
SELECT id, org_id, name, description, discount_type, discount_value, created_at, updated_at
FROM customer_groups
WHERE id = $1 AND deleted_at IS NULL
`

type GetCustomerGroupByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	DiscountType  pgtype.Text        `json:"discount_type"`
	DiscountValue pgtype.Numeric     `json:"discount_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerGroupByID(ctx context.Context, id pgtype.UUID) (GetCustomerGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerGroupByID, id)
	var i GetCustomerGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerGroupByName = `-- name: GetCustomerGroupByName :one
SELECT id, org_id, name, description, discount_type, discount_value, created_at, updated_at
FROM customer_groups
WHERE name = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetCustomerGroupByNameRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	DiscountType  pgtype.Text        `json:"discount_type"`
	DiscountValue pgtype.Numeric     `json:"discount_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCustomerGroupByName(ctx context.Context, name string) (GetCustomerGroupByNameRow, error) {
	row := q.db.QueryRow(ctx, getCustomerGroupByName, name)
	var i GetCustomerGroupByNameRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomerGroups = `-- name: ListCustomerGroups :many
SELECT id, org_id, name, description, discount_type, discount_value, created_at, updated_at
FROM customer_groups
WHERE deleted_at IS NULL
ORDER BY name ASC
`

type ListCustomerGroupsRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	DiscountType  pgtype.Text        `json:"discount_type"`
	DiscountValue pgtype.Numeric     `json:"discount_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCustomerGroups(ctx context.Context) ([]ListCustomerGroupsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerGroupsRow{}
	for rows.Next() {
		var i ListCustomerGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.DiscountType,
			&i.DiscountValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCustomerGroup = `-- name: SoftDeleteCustomerGroup :exec
UPDATE customer_groups
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCustomerGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCustomerGroup, id)
	return err
}

const updateCustomerGroup = `-- name: UpdateCustomerGroup :one
UPDATE customer_groups
SET name           = $1,
    description    = $2,
    discount_type  = $3,
    discount_value = $4,
    updated_at     = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, org_id, name, description, discount_type, discount_value, created_at, updated_at
`

type UpdateCustomerGroupParams struct {
	Name          string         `json:"name"`
	Description   pgtype.Text    `json:"description"`
	DiscountType  pgtype.Text    `json:"discount_type"`
	DiscountValue pgtype.Numeric `json:"discount_value"`
	ID            pgtype.UUID    `json:"id"`
}

type UpdateCustomerGroupRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	DiscountType  pgtype.Text        `json:"discount_type"`
	DiscountValue pgtype.Numeric     `json:"discount_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCustomerGroup(ctx context.Context, arg UpdateCustomerGroupParams) (UpdateCustomerGroupRow, error) {
	row := q.db.QueryRow(ctx, updateCustomerGroup,
		arg.Name,
		arg.Description,
		arg.DiscountType,
		arg.DiscountValue,
		arg.ID,
	)
	var i UpdateCustomerGroupRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
