// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO users (org_id, role_id, name, email, phone, password_hash, status)
VALUES ($1, $2, $3,
        $4, $5,
        $6, 'active')
RETURNING id
`

type CreateMemberParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	RoleID       pgtype.UUID `json:"role_id"`
	Name         string      `json:"name"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.OrgID,
		arg.RoleID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT u.id, u.org_id, u.name, u.email, u.phone, u.role_id, r.name AS role_name,
       u.status, u.created_at, u.updated_at
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetMemberByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	RoleID    pgtype.UUID        `json:"role_id"`
	RoleName  string             `json:"role_name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMemberByID(ctx context.Context, id pgtype.UUID) (GetMemberByIDRow, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i GetMemberByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.RoleID,
		&i.RoleName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT u.id, u.org_id, u.name, u.email, u.phone, u.role_id, r.name AS role_name,
       u.status, u.created_at, u.updated_at
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.deleted_at IS NULL
ORDER BY u.name ASC
`

type ListMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	RoleID    pgtype.UUID        `json:"role_id"`
	RoleName  string             `json:"role_name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMembers(ctx context.Context) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.RoleID,
			&i.RoleName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMember = `-- name: SoftDeleteMember :execrows
UPDATE users
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMember(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMember = `-- name: UpdateMember :execrows
UPDATE users
SET name       = $1,
    phone      = $2,
    role_id    = $3,
    status     = $4,
    updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateMemberParams struct {
	Name   string      `json:"name"`
	Phone  pgtype.Text `json:"phone"`
	RoleID pgtype.UUID `json:"role_id"`
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMember,
		arg.Name,
		arg.Phone,
		arg.RoleID,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
