// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      string             `json:"org_id"`
	Name       string             `json:"name"`
	Sku        string             `json:"sku"`
	PriceCents int64              `json:"price_cents"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
