// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFirstStoreIDForOrg = `-- name: GetFirstStoreIDForOrg :one
SELECT id
FROM stores
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstStoreIDForOrg(ctx context.Context, orgID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getFirstStoreIDForOrg, orgID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrderByExternalID = `-- name: GetOrderByExternalID :one
SELECT o.id,
       o.order_number,
       o.status,
       o.subtotal::TEXT       AS subtotal,
       o.tax_total::TEXT      AS tax_total,
       o.discount_total::TEXT AS discount_total,
       o.total::TEXT          AS total,
       COALESCE(o.notes, '')  AS notes,
       o.store_id,
       COALESCE(s.name, '')   AS store_name,
       o.register_id,
       o.user_id,
       COALESCE(u.name, '')   AS user_name,
       o.customer_id,
       COALESCE(c.name, '')         AS customer_name,
       o.created_at,
       o.completed_at,
       o.source,
       COALESCE(o.external_id, '')  AS external_id
FROM orders o
LEFT JOIN stores    s ON s.id = o.store_id    AND s.deleted_at IS NULL
LEFT JOIN users     u ON u.id = o.user_id     AND u.deleted_at IS NULL
LEFT JOIN customers c ON c.id = o.customer_id AND c.deleted_at IS NULL
WHERE o.source = $1
  AND o.external_id = $2
  AND o.deleted_at IS NULL
LIMIT 1
`

type GetOrderByExternalIDParams struct {
	Source     string      `json:"source"`
	ExternalID pgtype.Text `json:"external_id"`
}

type GetOrderByExternalIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrderNumber   string             `json:"order_number"`
	Status        string             `json:"status"`
	Subtotal      string             `json:"subtotal"`
	TaxTotal      string             `json:"tax_total"`
	DiscountTotal string             `json:"discount_total"`
	Total         string             `json:"total"`
	Notes         string             `json:"notes"`
	StoreID       pgtype.UUID        `json:"store_id"`
	StoreName     string             `json:"store_name"`
	RegisterID    pgtype.UUID        `json:"register_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	UserName      string             `json:"user_name"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	CustomerName  string             `json:"customer_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	Source        string             `json:"source"`
	ExternalID    string             `json:"external_id"`
}

func (q *Queries) GetOrderByExternalID(ctx context.Context, arg GetOrderByExternalIDParams) (GetOrderByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByExternalID, arg.Source, arg.ExternalID)
	var i GetOrderByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.TaxTotal,
		&i.DiscountTotal,
		&i.Total,
		&i.Notes,
		&i.StoreID,
		&i.StoreName,
		&i.RegisterID,
		&i.UserID,
		&i.UserName,
		&i.CustomerID,
		&i.CustomerName,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT o.id,
       o.order_number,
       o.status,
       o.subtotal::TEXT       AS subtotal,
       o.tax_total::TEXT      AS tax_total,
       o.discount_total::TEXT AS discount_total,
       o.total::TEXT          AS total,
       COALESCE(o.notes, '')  AS notes,
       o.store_id,
       COALESCE(s.name, '')   AS store_name,
       o.register_id,
       o.user_id,
       COALESCE(u.name, '')   AS user_name,
       o.customer_id,
       COALESCE(c.name, '')         AS customer_name,
       o.created_at,
       o.completed_at,
       o.source,
       COALESCE(o.external_id, '')  AS external_id
FROM orders o
LEFT JOIN stores    s ON s.id = o.store_id    AND s.deleted_at IS NULL
LEFT JOIN users     u ON u.id = o.user_id     AND u.deleted_at IS NULL
LEFT JOIN customers c ON c.id = o.customer_id AND c.deleted_at IS NULL
WHERE o.id = $1 AND o.deleted_at IS NULL
`

type GetOrderByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrderNumber   string             `json:"order_number"`
	Status        string             `json:"status"`
	Subtotal      string             `json:"subtotal"`
	TaxTotal      string             `json:"tax_total"`
	DiscountTotal string             `json:"discount_total"`
	Total         string             `json:"total"`
	Notes         string             `json:"notes"`
	StoreID       pgtype.UUID        `json:"store_id"`
	StoreName     string             `json:"store_name"`
	RegisterID    pgtype.UUID        `json:"register_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	UserName      string             `json:"user_name"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	CustomerName  string             `json:"customer_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	Source        string             `json:"source"`
	ExternalID    string             `json:"external_id"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.TaxTotal,
		&i.DiscountTotal,
		&i.Total,
		&i.Notes,
		&i.StoreID,
		&i.StoreName,
		&i.RegisterID,
		&i.UserID,
		&i.UserName,
		&i.CustomerID,
		&i.CustomerName,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (
    org_id, store_id, register_id, customer_id, user_id,
    order_number, status, subtotal, tax_total, discount_total, total,
    notes, completed_at, source, external_id, external_source_id
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7,
    $8::NUMERIC, $9::NUMERIC,
    $10::NUMERIC, $11::NUMERIC,
    $12, $13,
    $14, $15, $16
)
RETURNING id, org_id, store_id, register_id, customer_id, user_id,
          order_number, status,
          subtotal::TEXT       AS subtotal,
          tax_total::TEXT      AS tax_total,
          discount_total::TEXT AS discount_total,
          total::TEXT          AS total,
          COALESCE(notes, '')  AS notes,
          completed_at, source,
          COALESCE(external_id, '') AS external_id,
          created_at, updated_at
`

type InsertOrderParams struct {
	OrgID            pgtype.UUID        `json:"org_id"`
	StoreID          pgtype.UUID        `json:"store_id"`
	RegisterID       pgtype.UUID        `json:"register_id"`
	CustomerID       pgtype.UUID        `json:"customer_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OrderNumber      string             `json:"order_number"`
	Status           string             `json:"status"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	TaxTotal         pgtype.Numeric     `json:"tax_total"`
	DiscountTotal    pgtype.Numeric     `json:"discount_total"`
	Total            pgtype.Numeric     `json:"total"`
	Notes            pgtype.Text        `json:"notes"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	Source           string             `json:"source"`
	ExternalID       pgtype.Text        `json:"external_id"`
	ExternalSourceID pgtype.Text        `json:"external_source_id"`
}

type InsertOrderRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	StoreID       pgtype.UUID        `json:"store_id"`
	RegisterID    pgtype.UUID        `json:"register_id"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	OrderNumber   string             `json:"order_number"`
	Status        string             `json:"status"`
	Subtotal      string             `json:"subtotal"`
	TaxTotal      string             `json:"tax_total"`
	DiscountTotal string             `json:"discount_total"`
	Total         string             `json:"total"`
	Notes         string             `json:"notes"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	Source        string             `json:"source"`
	ExternalID    string             `json:"external_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (InsertOrderRow, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.OrgID,
		arg.StoreID,
		arg.RegisterID,
		arg.CustomerID,
		arg.UserID,
		arg.OrderNumber,
		arg.Status,
		arg.Subtotal,
		arg.TaxTotal,
		arg.DiscountTotal,
		arg.Total,
		arg.Notes,
		arg.CompletedAt,
		arg.Source,
		arg.ExternalID,
		arg.ExternalSourceID,
	)
	var i InsertOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.RegisterID,
		&i.CustomerID,
		&i.UserID,
		&i.OrderNumber,
		&i.Status,
		&i.Subtotal,
		&i.TaxTotal,
		&i.DiscountTotal,
		&i.Total,
		&i.Notes,
		&i.CompletedAt,
		&i.Source,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrderLineItem = `-- name: InsertOrderLineItem :exec
INSERT INTO order_line_items (
    org_id, order_id, variant_id, product_name, variant_name, sku,
    quantity, unit_price, tax_rate, tax_amount, discount_amount, line_total, notes
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7::NUMERIC, $8::NUMERIC,
    $9::NUMERIC, $10::NUMERIC,
    $11::NUMERIC, $12::NUMERIC,
    $13
)
`

type InsertOrderLineItemParams struct {
	OrgID          pgtype.UUID    `json:"org_id"`
	OrderID        pgtype.UUID    `json:"order_id"`
	VariantID      pgtype.UUID    `json:"variant_id"`
	ProductName    string         `json:"product_name"`
	VariantName    string         `json:"variant_name"`
	Sku            pgtype.Text    `json:"sku"`
	Quantity       pgtype.Numeric `json:"quantity"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	TaxRate        pgtype.Numeric `json:"tax_rate"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	LineTotal      pgtype.Numeric `json:"line_total"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) InsertOrderLineItem(ctx context.Context, arg InsertOrderLineItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderLineItem,
		arg.OrgID,
		arg.OrderID,
		arg.VariantID,
		arg.ProductName,
		arg.VariantName,
		arg.Sku,
		arg.Quantity,
		arg.UnitPrice,
		arg.TaxRate,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.LineTotal,
		arg.Notes,
	)
	return err
}

const insertOrderPayment = `-- name: InsertOrderPayment :exec
INSERT INTO payments (
    org_id, order_id, payment_method_id, amount, tendered, change_amount,
    reference, status
) VALUES (
    $1, $2, $3,
    $4::NUMERIC, $5::NUMERIC,
    $6::NUMERIC, $7,
    $8
)
`

type InsertOrderPaymentParams struct {
	OrgID           pgtype.UUID    `json:"org_id"`
	OrderID         pgtype.UUID    `json:"order_id"`
	PaymentMethodID pgtype.UUID    `json:"payment_method_id"`
	Amount          pgtype.Numeric `json:"amount"`
	Tendered        pgtype.Numeric `json:"tendered"`
	ChangeAmount    pgtype.Numeric `json:"change_amount"`
	Reference       pgtype.Text    `json:"reference"`
	Status          string         `json:"status"`
}

func (q *Queries) InsertOrderPayment(ctx context.Context, arg InsertOrderPaymentParams) error {
	_, err := q.db.Exec(ctx, insertOrderPayment,
		arg.OrgID,
		arg.OrderID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Tendered,
		arg.ChangeAmount,
		arg.Reference,
		arg.Status,
	)
	return err
}

const listOrderLineItems = `-- name: ListOrderLineItems :many
SELECT li.id,
       li.variant_id,
       li.product_name,
       li.variant_name,
       COALESCE(li.sku, '')        AS sku,
       li.quantity::TEXT           AS quantity,
       li.unit_price::TEXT         AS unit_price,
       li.tax_rate::TEXT           AS tax_rate,
       li.tax_amount::TEXT         AS tax_amount,
       li.discount_amount::TEXT    AS discount_amount,
       li.line_total::TEXT         AS line_total,
       COALESCE(li.notes, '')      AS notes
FROM order_line_items li
WHERE li.order_id = $1
ORDER BY li.created_at ASC
`

type ListOrderLineItemsRow struct {
	ID             pgtype.UUID `json:"id"`
	VariantID      pgtype.UUID `json:"variant_id"`
	ProductName    string      `json:"product_name"`
	VariantName    string      `json:"variant_name"`
	Sku            string      `json:"sku"`
	Quantity       string      `json:"quantity"`
	UnitPrice      string      `json:"unit_price"`
	TaxRate        string      `json:"tax_rate"`
	TaxAmount      string      `json:"tax_amount"`
	DiscountAmount string      `json:"discount_amount"`
	LineTotal      string      `json:"line_total"`
	Notes          string      `json:"notes"`
}

func (q *Queries) ListOrderLineItems(ctx context.Context, orderID pgtype.UUID) ([]ListOrderLineItemsRow, error) {
	rows, err := q.db.Query(ctx, listOrderLineItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderLineItemsRow{}
	for rows.Next() {
		var i ListOrderLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Sku,
			&i.Quantity,
			&i.UnitPrice,
			&i.TaxRate,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.LineTotal,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderPayments = `-- name: ListOrderPayments :many
SELECT p.id,
       p.payment_method_id,
       COALESCE(pm.name, '')            AS payment_method_name,
       p.amount::TEXT                   AS amount,
       COALESCE(p.tendered::TEXT, '')::TEXT      AS tendered,
       COALESCE(p.change_amount::TEXT, '')::TEXT AS change_amount,
       COALESCE(p.reference, '')        AS reference,
       p.status,
       p.created_at
FROM payments p
LEFT JOIN payment_methods pm ON pm.id = p.payment_method_id AND pm.deleted_at IS NULL
WHERE p.order_id = $1
ORDER BY p.created_at ASC
`

type ListOrderPaymentsRow struct {
	ID                pgtype.UUID        `json:"id"`
	PaymentMethodID   pgtype.UUID        `json:"payment_method_id"`
	PaymentMethodName string             `json:"payment_method_name"`
	Amount            string             `json:"amount"`
	Tendered          string             `json:"tendered"`
	ChangeAmount      string             `json:"change_amount"`
	Reference         string             `json:"reference"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOrderPayments(ctx context.Context, orderID pgtype.UUID) ([]ListOrderPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listOrderPayments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderPaymentsRow{}
	for rows.Next() {
		var i ListOrderPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentMethodID,
			&i.PaymentMethodName,
			&i.Amount,
			&i.Tendered,
			&i.ChangeAmount,
			&i.Reference,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByDateRange = `-- name: ListOrdersByDateRange :many
SELECT o.id,
       o.order_number,
       o.status,
       o.subtotal::TEXT       AS subtotal,
       o.tax_total::TEXT      AS tax_total,
       o.discount_total::TEXT AS discount_total,
       o.total::TEXT          AS total,
       o.store_id,
       COALESCE(s.name, '')   AS store_name,
       o.register_id,
       o.user_id,
       COALESCE(u.name, '')   AS user_name,
       o.customer_id,
       COALESCE(c.name, '')         AS customer_name,
       o.created_at,
       o.source,
       COALESCE(o.external_id, '')  AS external_id
FROM orders o
LEFT JOIN stores    s ON s.id = o.store_id    AND s.deleted_at IS NULL
LEFT JOIN users     u ON u.id = o.user_id     AND u.deleted_at IS NULL
LEFT JOIN customers c ON c.id = o.customer_id AND c.deleted_at IS NULL
WHERE o.deleted_at IS NULL
  AND o.created_at >= $1
  AND o.created_at <  $2
  AND ($3::UUID IS NULL OR o.store_id = $3)
ORDER BY o.created_at DESC
`

type ListOrdersByDateRangeParams struct {
	DateFrom pgtype.Timestamptz `json:"date_from"`
	DateTo   pgtype.Timestamptz `json:"date_to"`
	StoreID  pgtype.UUID        `json:"store_id"`
}

type ListOrdersByDateRangeRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrderNumber   string             `json:"order_number"`
	Status        string             `json:"status"`
	Subtotal      string             `json:"subtotal"`
	TaxTotal      string             `json:"tax_total"`
	DiscountTotal string             `json:"discount_total"`
	Total         string             `json:"total"`
	StoreID       pgtype.UUID        `json:"store_id"`
	StoreName     string             `json:"store_name"`
	RegisterID    pgtype.UUID        `json:"register_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	UserName      string             `json:"user_name"`
	CustomerID    pgtype.UUID        `json:"customer_id"`
	CustomerName  string             `json:"customer_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Source        string             `json:"source"`
	ExternalID    string             `json:"external_id"`
}

func (q *Queries) ListOrdersByDateRange(ctx context.Context, arg ListOrdersByDateRangeParams) ([]ListOrdersByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByDateRange, arg.DateFrom, arg.DateTo, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByDateRangeRow{}
	for rows.Next() {
		var i ListOrdersByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Status,
			&i.Subtotal,
			&i.TaxTotal,
			&i.DiscountTotal,
			&i.Total,
			&i.StoreID,
			&i.StoreName,
			&i.RegisterID,
			&i.UserID,
			&i.UserName,
			&i.CustomerID,
			&i.CustomerName,
			&i.CreatedAt,
			&i.Source,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
