// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one
INSERT INTO organizations (slug, name)
VALUES ($1, $2)
RETURNING id, slug, name, created_at, updated_at
`

type CreateOrgParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type CreateOrgRow struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (CreateOrgRow, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Slug, arg.Name)
	var i CreateOrgRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, slug, name, created_at, updated_at
FROM organizations
WHERE id = $1
`

type GetOrgByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrgByID(ctx context.Context, id pgtype.UUID) (GetOrgByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i GetOrgByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, slug, name, created_at, updated_at
FROM organizations
WHERE slug = $1
`

type GetOrgBySlugRow struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (GetOrgBySlugRow, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i GetOrgBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
