// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_method.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (org_id, name, type, is_active, sort_order)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, name, type, is_active, sort_order, created_at, updated_at
`

type CreatePaymentMethodParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	IsActive  bool        `json:"is_active"`
	SortOrder int32       `json:"sort_order"`
}

type CreatePaymentMethodRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	IsActive  bool               `json:"is_active"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (CreatePaymentMethodRow, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.IsActive,
		arg.SortOrder,
	)
	var i CreatePaymentMethodRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentMethods = `-- name: ListPaymentMethods :many
SELECT id, org_id, name, type, is_active, sort_order, created_at, updated_at
FROM payment_methods
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

type ListPaymentMethodsRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	IsActive  bool               `json:"is_active"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPaymentMethods(ctx context.Context) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentMethodsRow{}
	for rows.Next() {
		var i ListPaymentMethodsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePaymentMethod = `-- name: SoftDeletePaymentMethod :execrows
UPDATE payment_methods
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePaymentMethod(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePaymentMethod, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePaymentMethod = `-- name: UpdatePaymentMethod :one
UPDATE payment_methods
SET name       = $1,
    type       = $2,
    is_active  = $3,
    sort_order = $4,
    updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, org_id, name, type, is_active, sort_order, created_at, updated_at
`

type UpdatePaymentMethodParams struct {
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	IsActive  bool        `json:"is_active"`
	SortOrder int32       `json:"sort_order"`
	ID        pgtype.UUID `json:"id"`
}

type UpdatePaymentMethodRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	IsActive  bool               `json:"is_active"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (UpdatePaymentMethodRow, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethod,
		arg.Name,
		arg.Type,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	var i UpdatePaymentMethodRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
