// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase_order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPurchaseOrderItemReceived = `-- name: AddPurchaseOrderItemReceived :exec
UPDATE purchase_order_items
SET quantity_received = quantity_received + $1,
    updated_at        = now()
WHERE id = $2
`

type AddPurchaseOrderItemReceivedParams struct {
	Delta pgtype.Numeric `json:"delta"`
	ID    pgtype.UUID    `json:"id"`
}

func (q *Queries) AddPurchaseOrderItemReceived(ctx context.Context, arg AddPurchaseOrderItemReceivedParams) error {
	_, err := q.db.Exec(ctx, addPurchaseOrderItemReceived, arg.Delta, arg.ID)
	return err
}

const countPurchaseOrdersForPrefix = `-- name: CountPurchaseOrdersForPrefix :one
SELECT COUNT(*)::int AS n
FROM purchase_orders
WHERE org_id = $1
  AND po_number LIKE $2
`

type CountPurchaseOrdersForPrefixParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Prefix string      `json:"prefix"`
}

func (q *Queries) CountPurchaseOrdersForPrefix(ctx context.Context, arg CountPurchaseOrdersForPrefixParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrdersForPrefix, arg.OrgID, arg.Prefix)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (org_id, store_id, user_id, po_number, supplier_name, status, notes, expected_at)
VALUES ($1, $2, $3,
        $4, $5,
        'draft', $6, $7)
RETURNING id, org_id, store_id, user_id, po_number, supplier_name, status, notes,
          expected_at, received_at, created_at, updated_at
`

type CreatePurchaseOrderParams struct {
	OrgID        pgtype.UUID        `json:"org_id"`
	StoreID      pgtype.UUID        `json:"store_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PoNumber     string             `json:"po_number"`
	SupplierName pgtype.Text        `json:"supplier_name"`
	Notes        pgtype.Text        `json:"notes"`
	ExpectedAt   pgtype.Timestamptz `json:"expected_at"`
}

type CreatePurchaseOrderRow struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	StoreID      pgtype.UUID        `json:"store_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PoNumber     string             `json:"po_number"`
	SupplierName pgtype.Text        `json:"supplier_name"`
	Status       string             `json:"status"`
	Notes        pgtype.Text        `json:"notes"`
	ExpectedAt   pgtype.Timestamptz `json:"expected_at"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (CreatePurchaseOrderRow, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.OrgID,
		arg.StoreID,
		arg.UserID,
		arg.PoNumber,
		arg.SupplierName,
		arg.Notes,
		arg.ExpectedAt,
	)
	var i CreatePurchaseOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.UserID,
		&i.PoNumber,
		&i.SupplierName,
		&i.Status,
		&i.Notes,
		&i.ExpectedAt,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePurchaseOrderItemsByPO = `-- name: DeletePurchaseOrderItemsByPO :exec
DELETE FROM purchase_order_items
WHERE purchase_order_id = $1
`

func (q *Queries) DeletePurchaseOrderItemsByPO(ctx context.Context, purchaseOrderID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePurchaseOrderItemsByPO, purchaseOrderID)
	return err
}

const getPurchaseOrderByID = `-- name: GetPurchaseOrderByID :one
SELECT id, org_id, store_id, user_id, po_number, supplier_name, status, notes,
       expected_at, received_at, created_at, updated_at
FROM purchase_orders
WHERE id = $1 AND deleted_at IS NULL
`

type GetPurchaseOrderByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	StoreID      pgtype.UUID        `json:"store_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PoNumber     string             `json:"po_number"`
	SupplierName pgtype.Text        `json:"supplier_name"`
	Status       string             `json:"status"`
	Notes        pgtype.Text        `json:"notes"`
	ExpectedAt   pgtype.Timestamptz `json:"expected_at"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPurchaseOrderByID(ctx context.Context, id pgtype.UUID) (GetPurchaseOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderByID, id)
	var i GetPurchaseOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.UserID,
		&i.PoNumber,
		&i.SupplierName,
		&i.Status,
		&i.Notes,
		&i.ExpectedAt,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurchaseOrderItemByID = `-- name: GetPurchaseOrderItemByID :one
SELECT id, org_id, purchase_order_id, variant_id, quantity_ordered,
       quantity_received, cost_price, created_at, updated_at
FROM purchase_order_items
WHERE id = $1
`

func (q *Queries) GetPurchaseOrderItemByID(ctx context.Context, id pgtype.UUID) (PurchaseOrderItem, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrderItemByID, id)
	var i PurchaseOrderItem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PurchaseOrderID,
		&i.VariantID,
		&i.QuantityOrdered,
		&i.QuantityReceived,
		&i.CostPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPurchaseOrderItem = `-- name: InsertPurchaseOrderItem :one
INSERT INTO purchase_order_items (org_id, purchase_order_id, variant_id, quantity_ordered, cost_price)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, purchase_order_id, variant_id, quantity_ordered,
          quantity_received, cost_price, created_at, updated_at
`

type InsertPurchaseOrderItemParams struct {
	OrgID           pgtype.UUID    `json:"org_id"`
	PurchaseOrderID pgtype.UUID    `json:"purchase_order_id"`
	VariantID       pgtype.UUID    `json:"variant_id"`
	QuantityOrdered pgtype.Numeric `json:"quantity_ordered"`
	CostPrice       pgtype.Numeric `json:"cost_price"`
}

func (q *Queries) InsertPurchaseOrderItem(ctx context.Context, arg InsertPurchaseOrderItemParams) (PurchaseOrderItem, error) {
	row := q.db.QueryRow(ctx, insertPurchaseOrderItem,
		arg.OrgID,
		arg.PurchaseOrderID,
		arg.VariantID,
		arg.QuantityOrdered,
		arg.CostPrice,
	)
	var i PurchaseOrderItem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PurchaseOrderID,
		&i.VariantID,
		&i.QuantityOrdered,
		&i.QuantityReceived,
		&i.CostPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPurchaseOrderItems = `-- name: ListPurchaseOrderItems :many
SELECT poi.id, poi.org_id, poi.purchase_order_id, poi.variant_id,
       poi.quantity_ordered, poi.quantity_received, poi.cost_price,
       poi.created_at, poi.updated_at,
       pv.name AS variant_name, p.name AS product_name
FROM purchase_order_items poi
JOIN product_variants pv ON pv.id = poi.variant_id
JOIN products p ON p.id = pv.product_id
WHERE poi.purchase_order_id = $1
ORDER BY poi.created_at ASC
`

type ListPurchaseOrderItemsRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	PurchaseOrderID  pgtype.UUID        `json:"purchase_order_id"`
	VariantID        pgtype.UUID        `json:"variant_id"`
	QuantityOrdered  pgtype.Numeric     `json:"quantity_ordered"`
	QuantityReceived pgtype.Numeric     `json:"quantity_received"`
	CostPrice        pgtype.Numeric     `json:"cost_price"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	VariantName      string             `json:"variant_name"`
	ProductName      string             `json:"product_name"`
}

func (q *Queries) ListPurchaseOrderItems(ctx context.Context, purchaseOrderID pgtype.UUID) ([]ListPurchaseOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderItems, purchaseOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrderItemsRow{}
	for rows.Next() {
		var i ListPurchaseOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PurchaseOrderID,
			&i.VariantID,
			&i.QuantityOrdered,
			&i.QuantityReceived,
			&i.CostPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VariantName,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderSummaries = `-- name: ListPurchaseOrderSummaries :many
SELECT po.id,
       po.po_number,
       po.supplier_name,
       po.status,
       s.name AS store_name,
       po.expected_at,
       COUNT(poi.id)::INTEGER AS item_count,
       COALESCE(SUM(poi.quantity_ordered * poi.cost_price)::TEXT, '0') AS total,
       po.created_at
FROM purchase_orders po
LEFT JOIN stores s ON s.id = po.store_id AND s.deleted_at IS NULL
LEFT JOIN purchase_order_items poi ON poi.purchase_order_id = po.id
WHERE po.deleted_at IS NULL
GROUP BY po.id, po.po_number, po.supplier_name, po.status, s.name,
         po.expected_at, po.created_at
ORDER BY po.created_at DESC
`

type ListPurchaseOrderSummariesRow struct {
	ID           pgtype.UUID        `json:"id"`
	PoNumber     string             `json:"po_number"`
	SupplierName pgtype.Text        `json:"supplier_name"`
	Status       string             `json:"status"`
	StoreName    pgtype.Text        `json:"store_name"`
	ExpectedAt   pgtype.Timestamptz `json:"expected_at"`
	ItemCount    int32              `json:"item_count"`
	Total        interface{}        `json:"total"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPurchaseOrderSummaries(ctx context.Context) ([]ListPurchaseOrderSummariesRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrderSummariesRow{}
	for rows.Next() {
		var i ListPurchaseOrderSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.PoNumber,
			&i.SupplierName,
			&i.Status,
			&i.StoreName,
			&i.ExpectedAt,
			&i.ItemCount,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePurchaseOrder = `-- name: SoftDeletePurchaseOrder :exec
UPDATE purchase_orders
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePurchaseOrder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePurchaseOrder, id)
	return err
}

const updatePurchaseOrder = `-- name: UpdatePurchaseOrder :one
UPDATE purchase_orders
SET store_id      = $1,
    supplier_name = $2,
    notes         = $3,
    expected_at   = $4,
    updated_at    = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, org_id, store_id, user_id, po_number, supplier_name, status, notes,
          expected_at, received_at, created_at, updated_at
`

type UpdatePurchaseOrderParams struct {
	StoreID      pgtype.UUID        `json:"store_id"`
	SupplierName pgtype.Text        `json:"supplier_name"`
	Notes        pgtype.Text        `json:"notes"`
	ExpectedAt   pgtype.Timestamptz `json:"expected_at"`
	ID           pgtype.UUID        `json:"id"`
}

type UpdatePurchaseOrderRow struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	StoreID      pgtype.UUID        `json:"store_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PoNumber     string             `json:"po_number"`
	SupplierName pgtype.Text        `json:"supplier_name"`
	Status       string             `json:"status"`
	Notes        pgtype.Text        `json:"notes"`
	ExpectedAt   pgtype.Timestamptz `json:"expected_at"`
	ReceivedAt   pgtype.Timestamptz `json:"received_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePurchaseOrder(ctx context.Context, arg UpdatePurchaseOrderParams) (UpdatePurchaseOrderRow, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrder,
		arg.StoreID,
		arg.SupplierName,
		arg.Notes,
		arg.ExpectedAt,
		arg.ID,
	)
	var i UpdatePurchaseOrderRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.UserID,
		&i.PoNumber,
		&i.SupplierName,
		&i.Status,
		&i.Notes,
		&i.ExpectedAt,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePurchaseOrderStatus = `-- name: UpdatePurchaseOrderStatus :exec
UPDATE purchase_orders
SET status      = $1,
    received_at = $2,
    updated_at  = now()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdatePurchaseOrderStatusParams struct {
	Status     string             `json:"status"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updatePurchaseOrderStatus, arg.Status, arg.ReceivedAt, arg.ID)
	return err
}
