// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
