// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrg(ctx context.Context, arg CreateOrgParams) (CreateOrgRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetOrgByID(ctx context.Context, id pgtype.UUID) (GetOrgByIDRow, error)
	GetOrgBySlug(ctx context.Context, slug string) (GetOrgBySlugRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRoleByOrgAndName(ctx context.Context, arg GetRoleByOrgAndNameParams) (GetRoleByOrgAndNameRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListRolesByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListRolesByOrgRow, error)
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
