// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, org_id, token_hash, expires_at, user_agent)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, org_id, token_hash, expires_at, revoked_at, user_agent, created_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent string             `json:"user_agent"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.OrgID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, org_id, token_hash, expires_at, revoked_at, user_agent, created_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = $1
WHERE id = $2
`

type RevokeRefreshTokenParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.RevokedAt, arg.ID)
	return err
}
