// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (org_id, name, permissions, is_system)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, org_id, name, permissions, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Permissions []byte      `json:"permissions"`
	IsSystem    bool        `json:"is_system"`
}

type CreateRoleRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Permissions []byte             `json:"permissions"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.OrgID,
		arg.Name,
		arg.Permissions,
		arg.IsSystem,
	)
	var i CreateRoleRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByOrgAndName = `-- name: GetRoleByOrgAndName :one
SELECT id, org_id, name, permissions, is_system, created_at, updated_at
FROM roles
WHERE org_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetRoleByOrgAndNameParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Name  string      `json:"name"`
}

type GetRoleByOrgAndNameRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Permissions []byte             `json:"permissions"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRoleByOrgAndName(ctx context.Context, arg GetRoleByOrgAndNameParams) (GetRoleByOrgAndNameRow, error) {
	row := q.db.QueryRow(ctx, getRoleByOrgAndName, arg.OrgID, arg.Name)
	var i GetRoleByOrgAndNameRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesByOrg = `-- name: ListRolesByOrg :many
SELECT id, org_id, name, permissions, is_system, created_at, updated_at
FROM roles
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY is_system DESC, name ASC
`

type ListRolesByOrgRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Permissions []byte             `json:"permissions"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRolesByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListRolesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listRolesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesByOrgRow{}
	for rows.Next() {
		var i ListRolesByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Permissions,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
