// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_take.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockTake = `-- name: CreateStockTake :one
INSERT INTO stock_takes (org_id, store_id, user_id, status, notes)
VALUES ($1, $2, $3,
        'in_progress', $4)
RETURNING id, org_id, store_id, user_id, status, notes, completed_at,
          created_at, updated_at
`

type CreateStockTakeParams struct {
	OrgID   pgtype.UUID `json:"org_id"`
	StoreID pgtype.UUID `json:"store_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Notes   pgtype.Text `json:"notes"`
}

type CreateStockTakeRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	StoreID     pgtype.UUID        `json:"store_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      string             `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStockTake(ctx context.Context, arg CreateStockTakeParams) (CreateStockTakeRow, error) {
	row := q.db.QueryRow(ctx, createStockTake,
		arg.OrgID,
		arg.StoreID,
		arg.UserID,
		arg.Notes,
	)
	var i CreateStockTakeRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.UserID,
		&i.Status,
		&i.Notes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockTakeByID = `-- name: GetStockTakeByID :one
SELECT id, org_id, store_id, user_id, status, notes, completed_at,
       created_at, updated_at
FROM stock_takes
WHERE id = $1 AND deleted_at IS NULL
`

type GetStockTakeByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	StoreID     pgtype.UUID        `json:"store_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      string             `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetStockTakeByID(ctx context.Context, id pgtype.UUID) (GetStockTakeByIDRow, error) {
	row := q.db.QueryRow(ctx, getStockTakeByID, id)
	var i GetStockTakeByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StoreID,
		&i.UserID,
		&i.Status,
		&i.Notes,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertStockTakeItem = `-- name: InsertStockTakeItem :one
INSERT INTO stock_take_items (org_id, stock_take_id, variant_id, expected_qty, counted_qty)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, stock_take_id, variant_id, expected_qty, counted_qty,
          created_at, updated_at
`

type InsertStockTakeItemParams struct {
	OrgID       pgtype.UUID    `json:"org_id"`
	StockTakeID pgtype.UUID    `json:"stock_take_id"`
	VariantID   pgtype.UUID    `json:"variant_id"`
	ExpectedQty pgtype.Numeric `json:"expected_qty"`
	CountedQty  pgtype.Numeric `json:"counted_qty"`
}

func (q *Queries) InsertStockTakeItem(ctx context.Context, arg InsertStockTakeItemParams) (StockTakeItem, error) {
	row := q.db.QueryRow(ctx, insertStockTakeItem,
		arg.OrgID,
		arg.StockTakeID,
		arg.VariantID,
		arg.ExpectedQty,
		arg.CountedQty,
	)
	var i StockTakeItem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.StockTakeID,
		&i.VariantID,
		&i.ExpectedQty,
		&i.CountedQty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStockTakeItems = `-- name: ListStockTakeItems :many
SELECT sti.id, sti.org_id, sti.stock_take_id, sti.variant_id,
       sti.expected_qty, sti.counted_qty, sti.created_at, sti.updated_at,
       pv.name AS variant_name, p.name AS product_name
FROM stock_take_items sti
JOIN product_variants pv ON pv.id = sti.variant_id
JOIN products p ON p.id = pv.product_id
WHERE sti.stock_take_id = $1
ORDER BY p.name ASC, pv.sort_order ASC
`

type ListStockTakeItemsRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	StockTakeID pgtype.UUID        `json:"stock_take_id"`
	VariantID   pgtype.UUID        `json:"variant_id"`
	ExpectedQty pgtype.Numeric     `json:"expected_qty"`
	CountedQty  pgtype.Numeric     `json:"counted_qty"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	VariantName string             `json:"variant_name"`
	ProductName string             `json:"product_name"`
}

func (q *Queries) ListStockTakeItems(ctx context.Context, stockTakeID pgtype.UUID) ([]ListStockTakeItemsRow, error) {
	rows, err := q.db.Query(ctx, listStockTakeItems, stockTakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockTakeItemsRow{}
	for rows.Next() {
		var i ListStockTakeItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.StockTakeID,
			&i.VariantID,
			&i.ExpectedQty,
			&i.CountedQty,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VariantName,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockTakeSummaries = `-- name: ListStockTakeSummaries :many
SELECT st.id,
       s.name AS store_name,
       st.status,
       COUNT(sti.id)::INTEGER AS item_count,
       COUNT(sti.id) FILTER (WHERE sti.counted_qty != sti.expected_qty)::INTEGER AS variance_lines,
       st.created_at,
       st.completed_at
FROM stock_takes st
LEFT JOIN stores s ON s.id = st.store_id AND s.deleted_at IS NULL
LEFT JOIN stock_take_items sti ON sti.stock_take_id = st.id
WHERE st.deleted_at IS NULL
GROUP BY st.id, s.name, st.status, st.created_at, st.completed_at
ORDER BY st.created_at DESC
`

type ListStockTakeSummariesRow struct {
	ID            pgtype.UUID        `json:"id"`
	StoreName     pgtype.Text        `json:"store_name"`
	Status        string             `json:"status"`
	ItemCount     int32              `json:"item_count"`
	VarianceLines int32              `json:"variance_lines"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListStockTakeSummaries(ctx context.Context) ([]ListStockTakeSummariesRow, error) {
	rows, err := q.db.Query(ctx, listStockTakeSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockTakeSummariesRow{}
	for rows.Next() {
		var i ListStockTakeSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreName,
			&i.Status,
			&i.ItemCount,
			&i.VarianceLines,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedStockTakeItemsFromOnHand = `-- name: SeedStockTakeItemsFromOnHand :exec
INSERT INTO stock_take_items (org_id, stock_take_id, variant_id, expected_qty, counted_qty)
SELECT $1, $2, v.id,
       COALESCE(SUM(CASE WHEN sm.direction='in' THEN sm.quantity ELSE -sm.quantity END), 0),
       0
FROM product_variants v
LEFT JOIN stock_movements sm
    ON sm.variant_id = v.id
   AND sm.store_id = $3
   AND sm.deleted_at IS NULL
WHERE v.is_active = TRUE
GROUP BY v.id
`

type SeedStockTakeItemsFromOnHandParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	StockTakeID pgtype.UUID `json:"stock_take_id"`
	StoreID     pgtype.UUID `json:"store_id"`
}

// Seeds stock_take_items from current on-hand for all active variants in the
// given store. Expected qty comes from SUM of stock_movements (in - out).
func (q *Queries) SeedStockTakeItemsFromOnHand(ctx context.Context, arg SeedStockTakeItemsFromOnHandParams) error {
	_, err := q.db.Exec(ctx, seedStockTakeItemsFromOnHand, arg.OrgID, arg.StockTakeID, arg.StoreID)
	return err
}

const softDeleteStockTake = `-- name: SoftDeleteStockTake :exec
UPDATE stock_takes
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteStockTake(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStockTake, id)
	return err
}

const updateStockTakeItemCount = `-- name: UpdateStockTakeItemCount :exec
UPDATE stock_take_items
SET counted_qty = $1, updated_at = now()
WHERE id = $2
`

type UpdateStockTakeItemCountParams struct {
	CountedQty pgtype.Numeric `json:"counted_qty"`
	ID         pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateStockTakeItemCount(ctx context.Context, arg UpdateStockTakeItemCountParams) error {
	_, err := q.db.Exec(ctx, updateStockTakeItemCount, arg.CountedQty, arg.ID)
	return err
}

const updateStockTakeNotes = `-- name: UpdateStockTakeNotes :exec
UPDATE stock_takes
SET notes = $1, updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateStockTakeNotesParams struct {
	Notes pgtype.Text `json:"notes"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateStockTakeNotes(ctx context.Context, arg UpdateStockTakeNotesParams) error {
	_, err := q.db.Exec(ctx, updateStockTakeNotes, arg.Notes, arg.ID)
	return err
}

const updateStockTakeStatus = `-- name: UpdateStockTakeStatus :exec
UPDATE stock_takes
SET status = $1,
    completed_at = $2,
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateStockTakeStatusParams struct {
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateStockTakeStatus(ctx context.Context, arg UpdateStockTakeStatusParams) error {
	_, err := q.db.Exec(ctx, updateStockTakeStatus, arg.Status, arg.CompletedAt, arg.ID)
	return err
}
