// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_movement.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertStockMovement = `-- name: InsertStockMovement :one
INSERT INTO stock_movements (org_id, store_id, register_id, variant_id, direction,
    quantity, movement_type, reference_type, reference_id, user_id, notes)
VALUES ($1, $2, $3,
        $4, $5, $6,
        $7, $8,
        $9, $10, $11)
RETURNING id
`

type InsertStockMovementParams struct {
	OrgID         pgtype.UUID    `json:"org_id"`
	StoreID       pgtype.UUID    `json:"store_id"`
	RegisterID    pgtype.UUID    `json:"register_id"`
	VariantID     pgtype.UUID    `json:"variant_id"`
	Direction     string         `json:"direction"`
	Quantity      pgtype.Numeric `json:"quantity"`
	MovementType  string         `json:"movement_type"`
	ReferenceType pgtype.Text    `json:"reference_type"`
	ReferenceID   pgtype.UUID    `json:"reference_id"`
	UserID        pgtype.UUID    `json:"user_id"`
	Notes         pgtype.Text    `json:"notes"`
}

func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertStockMovement,
		arg.OrgID,
		arg.StoreID,
		arg.RegisterID,
		arg.VariantID,
		arg.Direction,
		arg.Quantity,
		arg.MovementType,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.UserID,
		arg.Notes,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
