// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (org_id, name, address, phone, email, timezone, status)
VALUES ($1, $2,
        $3, $4, $5,
        $6, $7)
RETURNING id, org_id, name, address, phone, email, timezone, status, created_at, updated_at
`

type CreateStoreParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	Email    pgtype.Text `json:"email"`
	Timezone pgtype.Text `json:"timezone"`
	Status   string      `json:"status"`
}

type CreateStoreRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	Timezone  pgtype.Text        `json:"timezone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (CreateStoreRow, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.OrgID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Timezone,
		arg.Status,
	)
	var i CreateStoreRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstStoreForOrg = `-- name: GetFirstStoreForOrg :one
SELECT id, org_id, name, address, phone, email, timezone, status, created_at, updated_at
FROM stores
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT 1
`

type GetFirstStoreForOrgRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	Timezone  pgtype.Text        `json:"timezone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFirstStoreForOrg(ctx context.Context, orgID pgtype.UUID) (GetFirstStoreForOrgRow, error) {
	row := q.db.QueryRow(ctx, getFirstStoreForOrg, orgID)
	var i GetFirstStoreForOrgRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStoreRefs = `-- name: ListStoreRefs :many
SELECT id, name
FROM stores
WHERE deleted_at IS NULL
ORDER BY name ASC
`

type ListStoreRefsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListStoreRefs(ctx context.Context) ([]ListStoreRefsRow, error) {
	rows, err := q.db.Query(ctx, listStoreRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoreRefsRow{}
	for rows.Next() {
		var i ListStoreRefsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStores = `-- name: ListStores :many
SELECT id, org_id, name, address, phone, email, timezone, status, created_at, updated_at
FROM stores
WHERE deleted_at IS NULL
ORDER BY name ASC
`

type ListStoresRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	Timezone  pgtype.Text        `json:"timezone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListStores(ctx context.Context) ([]ListStoresRow, error) {
	rows, err := q.db.Query(ctx, listStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoresRow{}
	for rows.Next() {
		var i ListStoresRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.Timezone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantPickerItems = `-- name: ListVariantPickerItems :many
SELECT v.id,
       p.name AS product_name,
       v.name AS variant_name,
       COALESCE(v.sku, '') AS sku,
       v.price::TEXT AS price,
       v.cost_price::TEXT AS cost_price
FROM product_variants v
JOIN products p ON p.id = v.product_id
WHERE v.is_active = TRUE
  AND v.deleted_at IS NULL
  AND p.is_active = TRUE
  AND p.deleted_at IS NULL
ORDER BY p.name ASC, v.sort_order ASC
`

type ListVariantPickerItemsRow struct {
	ID          pgtype.UUID `json:"id"`
	ProductName string      `json:"product_name"`
	VariantName string      `json:"variant_name"`
	Sku         string      `json:"sku"`
	Price       string      `json:"price"`
	CostPrice   string      `json:"cost_price"`
}

func (q *Queries) ListVariantPickerItems(ctx context.Context) ([]ListVariantPickerItemsRow, error) {
	rows, err := q.db.Query(ctx, listVariantPickerItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantPickerItemsRow{}
	for rows.Next() {
		var i ListVariantPickerItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.VariantName,
			&i.Sku,
			&i.Price,
			&i.CostPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStore = `-- name: SoftDeleteStore :execrows
UPDATE stores
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteStore(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteStore, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET name       = $1,
    address    = $2,
    phone      = $3,
    email      = $4,
    timezone   = $5,
    status     = $6,
    updated_at = now()
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, org_id, name, address, phone, email, timezone, status, created_at, updated_at
`

type UpdateStoreParams struct {
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	Email    pgtype.Text `json:"email"`
	Timezone pgtype.Text `json:"timezone"`
	Status   string      `json:"status"`
	ID       pgtype.UUID `json:"id"`
}

type UpdateStoreRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	Timezone  pgtype.Text        `json:"timezone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (UpdateStoreRow, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Timezone,
		arg.Status,
		arg.ID,
	)
	var i UpdateStoreRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
