// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplier.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (org_id, name, contact_name, email, phone, address, notes)
VALUES ($1, $2, $3,
        $4, $5, $6, $7)
RETURNING id, org_id, name, contact_name, email, phone, address, notes, created_at, updated_at
`

type CreateSupplierParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	ContactName pgtype.Text `json:"contact_name"`
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	Address     pgtype.Text `json:"address"`
	Notes       pgtype.Text `json:"notes"`
}

type CreateSupplierRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	ContactName pgtype.Text        `json:"contact_name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Address     pgtype.Text        `json:"address"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (CreateSupplierRow, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.OrgID,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Notes,
	)
	var i CreateSupplierRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, org_id, name, contact_name, email, phone, address, notes, created_at, updated_at
FROM suppliers
WHERE id = $1 AND deleted_at IS NULL
`

type GetSupplierByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	ContactName pgtype.Text        `json:"contact_name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Address     pgtype.Text        `json:"address"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSupplierByID(ctx context.Context, id pgtype.UUID) (GetSupplierByIDRow, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i GetSupplierByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, org_id, name, contact_name, email, phone, address, notes, created_at, updated_at
FROM suppliers
WHERE deleted_at IS NULL
ORDER BY name ASC
`

type ListSuppliersRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	ContactName pgtype.Text        `json:"contact_name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Address     pgtype.Text        `json:"address"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSuppliers(ctx context.Context) ([]ListSuppliersRow, error) {
	rows, err := q.db.Query(ctx, listSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuppliersRow{}
	for rows.Next() {
		var i ListSuppliersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSupplier = `-- name: SoftDeleteSupplier :exec
UPDATE suppliers
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSupplier(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSupplier, id)
	return err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name         = $1,
    contact_name = $2,
    email        = $3,
    phone        = $4,
    address      = $5,
    notes        = $6,
    updated_at   = now()
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, org_id, name, contact_name, email, phone, address, notes, created_at, updated_at
`

type UpdateSupplierParams struct {
	Name        string      `json:"name"`
	ContactName pgtype.Text `json:"contact_name"`
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	Address     pgtype.Text `json:"address"`
	Notes       pgtype.Text `json:"notes"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateSupplierRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	ContactName pgtype.Text        `json:"contact_name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Address     pgtype.Text        `json:"address"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (UpdateSupplierRow, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Notes,
		arg.ID,
	)
	var i UpdateSupplierRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
