// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tax_class.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultTaxClasses = `-- name: ClearDefaultTaxClasses :exec
UPDATE tax_classes
SET is_default = FALSE, updated_at = now()
WHERE is_default = TRUE AND deleted_at IS NULL
`

func (q *Queries) ClearDefaultTaxClasses(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultTaxClasses)
	return err
}

const createTaxClass = `-- name: CreateTaxClass :one
INSERT INTO tax_classes (org_id, name, description, is_default, sort_order)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, name, description, is_default, sort_order, created_at, updated_at
`

type CreateTaxClassParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsDefault   bool        `json:"is_default"`
	SortOrder   int32       `json:"sort_order"`
}

type CreateTaxClassRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsDefault   bool               `json:"is_default"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTaxClass(ctx context.Context, arg CreateTaxClassParams) (CreateTaxClassRow, error) {
	row := q.db.QueryRow(ctx, createTaxClass,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.IsDefault,
		arg.SortOrder,
	)
	var i CreateTaxClassRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxClass = `-- name: GetTaxClass :one
SELECT id, org_id, name, description, is_default, sort_order, created_at, updated_at
FROM tax_classes
WHERE id = $1 AND deleted_at IS NULL
`

type GetTaxClassRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsDefault   bool               `json:"is_default"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTaxClass(ctx context.Context, id pgtype.UUID) (GetTaxClassRow, error) {
	row := q.db.QueryRow(ctx, getTaxClass, id)
	var i GetTaxClassRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTaxClassRate = `-- name: InsertTaxClassRate :one
INSERT INTO tax_class_rates (org_id, tax_class_id, tax_rate_id, sequence, is_compound)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, tax_class_id, tax_rate_id, sequence, is_compound, created_at, updated_at
`

type InsertTaxClassRateParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	TaxClassID pgtype.UUID `json:"tax_class_id"`
	TaxRateID  pgtype.UUID `json:"tax_rate_id"`
	Sequence   int32       `json:"sequence"`
	IsCompound bool        `json:"is_compound"`
}

type InsertTaxClassRateRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	TaxClassID pgtype.UUID        `json:"tax_class_id"`
	TaxRateID  pgtype.UUID        `json:"tax_rate_id"`
	Sequence   int32              `json:"sequence"`
	IsCompound bool               `json:"is_compound"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertTaxClassRate(ctx context.Context, arg InsertTaxClassRateParams) (InsertTaxClassRateRow, error) {
	row := q.db.QueryRow(ctx, insertTaxClassRate,
		arg.OrgID,
		arg.TaxClassID,
		arg.TaxRateID,
		arg.Sequence,
		arg.IsCompound,
	)
	var i InsertTaxClassRateRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TaxClassID,
		&i.TaxRateID,
		&i.Sequence,
		&i.IsCompound,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaxClassRatesByClassIDs = `-- name: ListTaxClassRatesByClassIDs :many
SELECT id, org_id, tax_class_id, tax_rate_id, sequence, is_compound, created_at, updated_at
FROM tax_class_rates
WHERE tax_class_id = ANY($1::UUID[]) AND deleted_at IS NULL
ORDER BY tax_class_id, sequence
`

type ListTaxClassRatesByClassIDsRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	TaxClassID pgtype.UUID        `json:"tax_class_id"`
	TaxRateID  pgtype.UUID        `json:"tax_rate_id"`
	Sequence   int32              `json:"sequence"`
	IsCompound bool               `json:"is_compound"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTaxClassRatesByClassIDs(ctx context.Context, classIds []pgtype.UUID) ([]ListTaxClassRatesByClassIDsRow, error) {
	rows, err := q.db.Query(ctx, listTaxClassRatesByClassIDs, classIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxClassRatesByClassIDsRow{}
	for rows.Next() {
		var i ListTaxClassRatesByClassIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TaxClassID,
			&i.TaxRateID,
			&i.Sequence,
			&i.IsCompound,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxClasses = `-- name: ListTaxClasses :many
SELECT id, org_id, name, description, is_default, sort_order, created_at, updated_at
FROM tax_classes
WHERE deleted_at IS NULL
ORDER BY is_default DESC, sort_order ASC, name ASC
`

type ListTaxClassesRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsDefault   bool               `json:"is_default"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTaxClasses(ctx context.Context) ([]ListTaxClassesRow, error) {
	rows, err := q.db.Query(ctx, listTaxClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxClassesRow{}
	for rows.Next() {
		var i ListTaxClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTaxClass = `-- name: SoftDeleteTaxClass :execrows
UPDATE tax_classes
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTaxClass(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTaxClass, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteTaxClassRatesByClassID = `-- name: SoftDeleteTaxClassRatesByClassID :exec
UPDATE tax_class_rates
SET deleted_at = now(), updated_at = now()
WHERE tax_class_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTaxClassRatesByClassID(ctx context.Context, taxClassID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTaxClassRatesByClassID, taxClassID)
	return err
}

const updateTaxClass = `-- name: UpdateTaxClass :one
UPDATE tax_classes
SET name        = $1,
    description = $2,
    is_default  = $3,
    sort_order  = $4,
    updated_at  = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, org_id, name, description, is_default, sort_order, created_at, updated_at
`

type UpdateTaxClassParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsDefault   bool        `json:"is_default"`
	SortOrder   int32       `json:"sort_order"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateTaxClassRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsDefault   bool               `json:"is_default"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTaxClass(ctx context.Context, arg UpdateTaxClassParams) (UpdateTaxClassRow, error) {
	row := q.db.QueryRow(ctx, updateTaxClass,
		arg.Name,
		arg.Description,
		arg.IsDefault,
		arg.SortOrder,
		arg.ID,
	)
	var i UpdateTaxClassRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
