// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tax_rate.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultTaxRates = `-- name: ClearDefaultTaxRates :exec
UPDATE tax_rates
SET is_default = FALSE, updated_at = now()
WHERE is_default = TRUE AND deleted_at IS NULL
`

func (q *Queries) ClearDefaultTaxRates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearDefaultTaxRates)
	return err
}

const createTaxRate = `-- name: CreateTaxRate :one
INSERT INTO tax_rates (org_id, name, rate, is_inclusive, is_default)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, org_id, name, rate, is_inclusive, is_default, created_at, updated_at
`

type CreateTaxRateParams struct {
	OrgID       pgtype.UUID    `json:"org_id"`
	Name        string         `json:"name"`
	Rate        pgtype.Numeric `json:"rate"`
	IsInclusive bool           `json:"is_inclusive"`
	IsDefault   bool           `json:"is_default"`
}

type CreateTaxRateRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Rate        pgtype.Numeric     `json:"rate"`
	IsInclusive bool               `json:"is_inclusive"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTaxRate(ctx context.Context, arg CreateTaxRateParams) (CreateTaxRateRow, error) {
	row := q.db.QueryRow(ctx, createTaxRate,
		arg.OrgID,
		arg.Name,
		arg.Rate,
		arg.IsInclusive,
		arg.IsDefault,
	)
	var i CreateTaxRateRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Rate,
		&i.IsInclusive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaxRates = `-- name: ListTaxRates :many
SELECT id, org_id, name, rate, is_inclusive, is_default, created_at, updated_at
FROM tax_rates
WHERE deleted_at IS NULL
ORDER BY is_default DESC, name ASC
`

type ListTaxRatesRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Rate        pgtype.Numeric     `json:"rate"`
	IsInclusive bool               `json:"is_inclusive"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTaxRates(ctx context.Context) ([]ListTaxRatesRow, error) {
	rows, err := q.db.Query(ctx, listTaxRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaxRatesRow{}
	for rows.Next() {
		var i ListTaxRatesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Rate,
			&i.IsInclusive,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTaxRate = `-- name: SoftDeleteTaxRate :execrows
UPDATE tax_rates
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTaxRate(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTaxRate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTaxRate = `-- name: UpdateTaxRate :one
UPDATE tax_rates
SET name         = $1,
    rate         = $2,
    is_inclusive = $3,
    is_default   = $4,
    updated_at   = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, org_id, name, rate, is_inclusive, is_default, created_at, updated_at
`

type UpdateTaxRateParams struct {
	Name        string         `json:"name"`
	Rate        pgtype.Numeric `json:"rate"`
	IsInclusive bool           `json:"is_inclusive"`
	IsDefault   bool           `json:"is_default"`
	ID          pgtype.UUID    `json:"id"`
}

type UpdateTaxRateRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Rate        pgtype.Numeric     `json:"rate"`
	IsInclusive bool               `json:"is_inclusive"`
	IsDefault   bool               `json:"is_default"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTaxRate(ctx context.Context, arg UpdateTaxRateParams) (UpdateTaxRateRow, error) {
	row := q.db.QueryRow(ctx, updateTaxRate,
		arg.Name,
		arg.Rate,
		arg.IsInclusive,
		arg.IsDefault,
		arg.ID,
	)
	var i UpdateTaxRateRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Rate,
		&i.IsInclusive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
