// Code generated by wire. DO NOT EDIT.

//go:generate go run github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"fmt"

	"github.com/genpick/genpos-mono/backend/internal/config"
	"github.com/genpick/genpos-mono/backend/internal/handler"
	grpchandler "github.com/genpick/genpos-mono/backend/internal/handler/grpc"
	"github.com/genpick/genpos-mono/backend/internal/infrastructure/datastore"
	"github.com/genpick/genpos-mono/backend/internal/usecase"
	"github.com/genpick/genpos-mono/backend/pkg/database"
	"github.com/genpick/genpos-mono/backend/pkg/log"
)

// InitializeApp creates a fully wired application.
func InitializeApp(ctx context.Context, cfg *config.Config) (*App, error) {
	logger := log.NewLogger(cfg.Log, nil)
	log.SetDefault(logger)

	db, err := database.NewPostgresDB(ctx, cfg.Database)
	if err != nil {
		return nil, fmt.Errorf("database: %w", err)
	}

	authDB, err := database.NewPostgresDB(ctx, cfg.AuthDatabase())
	if err != nil {
		return nil, fmt.Errorf("auth database: %w", err)
	}

	tenantDB := datastore.NewTenantDB(db.Pool)
	// Auth flows (login, registration, refresh) need cross-tenant SELECTs
	// before an org is known; they run on the BYPASSRLS auth pool.
	txManager := datastore.NewTxManager(authDB.Pool)

	server := handler.NewServer(logger)

	// Catalog
	categoryReader := datastore.NewCategoryReader()
	categoryWriter := datastore.NewCategoryWriter()
	productDetailReader := datastore.NewProductDetailReader()
	productWriter := datastore.NewProductWriter()
	catalogUsecase := usecase.NewCatalogUsecase(
		tenantDB, categoryReader, categoryWriter, productDetailReader, productWriter,
	)
	catalogHandler := grpchandler.NewCatalogHandler(logger, catalogUsecase)

	// Customers
	customerReader := datastore.NewCustomerReader()
	customerWriter := datastore.NewCustomerWriter()
	customerGroupReader := datastore.NewCustomerGroupReader()
	customerGroupWriter := datastore.NewCustomerGroupWriter()
	customerUsecase := usecase.NewCustomerUsecase(
		tenantDB, customerReader, customerWriter, customerGroupReader, customerGroupWriter,
	)
	customerHandler := grpchandler.NewCustomerHandler(logger, customerUsecase)

	// Inventory — suppliers + purchase orders
	supplierReader := datastore.NewSupplierReader()
	supplierWriter := datastore.NewSupplierWriter()
	supplierUsecase := usecase.NewSupplierUsecase(tenantDB, supplierReader, supplierWriter)
	supplierHandler := grpchandler.NewSupplierHandler(logger, supplierUsecase)

	poReader := datastore.NewPurchaseOrderReader()
	poWriter := datastore.NewPurchaseOrderWriter()
	stockMovementWriter := datastore.NewStockMovementWriter()
	poUsecase := usecase.NewPurchaseOrderUsecase(tenantDB, poReader, poWriter, stockMovementWriter)
	poHandler := grpchandler.NewPurchaseOrderHandler(logger, poUsecase)

	orderReader := datastore.NewOrderReader()
	orderWriter := datastore.NewOrderWriter()
	orgStoreReader := datastore.NewOrgStoreReader()
	orderMemberReader := datastore.NewMemberReader()
	orderUsecase := usecase.NewOrderUsecase(tenantDB, orderReader, orderWriter, orgStoreReader, orderMemberReader)
	orderHandler := grpchandler.NewOrderHandler(logger, orderUsecase)

	stockTakeReader := datastore.NewStockTakeReader()
	stockTakeWriter := datastore.NewStockTakeWriter()
	stockTakeUsecase := usecase.NewStockTakeUsecase(tenantDB, stockTakeReader, stockTakeWriter, stockMovementWriter)
	stockTakeHandler := grpchandler.NewStockTakeHandler(logger, stockTakeUsecase)

	// Stores (settings)
	storeReader := datastore.NewStoreReader()
	storeWriter := datastore.NewStoreWriter()
	storeUsecase := usecase.NewStoreUsecase(tenantDB, storeReader, storeWriter)
	storeHandler := grpchandler.NewStoreHandler(logger, storeUsecase)

	// Payment methods (settings)
	pmReader := datastore.NewPaymentMethodReader()
	pmWriter := datastore.NewPaymentMethodWriter()
	pmUsecase := usecase.NewPaymentMethodUsecase(tenantDB, pmReader, pmWriter)
	pmHandler := grpchandler.NewPaymentMethodHandler(logger, pmUsecase)

	// Tax rates (settings)
	trReader := datastore.NewTaxRateReader()
	trWriter := datastore.NewTaxRateWriter()
	trUsecase := usecase.NewTaxRateUsecase(tenantDB, trReader, trWriter)
	trHandler := grpchandler.NewTaxRateHandler(logger, trUsecase)

	// Members (users)
	memberReader := datastore.NewMemberReader()
	memberWriter := datastore.NewMemberWriter()
	memberUsecase := usecase.NewMemberUsecase(tenantDB, memberReader, memberWriter)
	memberHandler := grpchandler.NewMemberHandler(logger, memberUsecase)

	// Auth
	userReader := datastore.NewUserReader()
	userWriter := datastore.NewUserWriter()
	orgReader := datastore.NewOrgReader()
	orgWriter := datastore.NewOrgWriter()
	roleReader := datastore.NewRoleReader()
	roleWriter := datastore.NewRoleWriter()
	refreshReader := datastore.NewRefreshTokenReader()
	refreshWriter := datastore.NewRefreshTokenWriter()
	authUsecase := usecase.NewAuthUsecase(
		cfg, txManager,
		userReader, userWriter,
		orgReader, orgWriter,
		roleReader, roleWriter,
		storeWriter,
		categoryWriter, pmWriter,
		refreshReader, refreshWriter,
	)
	authHandler := grpchandler.NewAuthHandler(cfg, logger, authUsecase)

	return &App{
		Logger:               logger,
		Server:               server,
		AuthHandler:          authHandler,
		CatalogHandler:       catalogHandler,
		CustomerHandler:      customerHandler,
		SupplierHandler:      supplierHandler,
		PurchaseOrderHandler: poHandler,
		OrderHandler:         orderHandler,
		StockTakeHandler:     stockTakeHandler,
		StoreHandler:         storeHandler,
		PaymentMethodHandler: pmHandler,
		TaxRateHandler:       trHandler,
		MemberHandler:        memberHandler,
		DB:                   db,
		AuthDB:               authDB,
		Config:               cfg,
	}, nil
}
