// Code generated by wire. DO NOT EDIT.

//go:generate go run github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"fmt"

	"github.com/genpick/genpos-mono/backend/internal/config"
	"github.com/genpick/genpos-mono/backend/internal/handler"
	grpchandler "github.com/genpick/genpos-mono/backend/internal/handler/grpc"
	"github.com/genpick/genpos-mono/backend/internal/infrastructure/datastore"
	"github.com/genpick/genpos-mono/backend/internal/usecase"
	"github.com/genpick/genpos-mono/backend/pkg/database"
	"github.com/genpick/genpos-mono/backend/pkg/log"
)

// InitializeApp creates a fully wired application.
func InitializeApp(ctx context.Context, cfg *config.Config) (*App, error) {
	logger := log.NewLogger(cfg.Log, nil)
	log.SetDefault(logger)

	db, err := database.NewPostgresDB(ctx, cfg.Database)
	if err != nil {
		return nil, fmt.Errorf("database: %w", err)
	}

	pool := db.Pool
	tenantDB := datastore.NewTenantDB(pool)
	txManager := datastore.NewTxManager(pool)

	// Catalog
	productReader := datastore.NewProductReader()
	productUsecase := usecase.NewProductUsecase(tenantDB, productReader)
	server := handler.NewServer(logger, productUsecase)

	// Auth
	userReader := datastore.NewUserReader()
	userWriter := datastore.NewUserWriter()
	orgReader := datastore.NewOrgReader()
	orgWriter := datastore.NewOrgWriter()
	roleReader := datastore.NewRoleReader()
	roleWriter := datastore.NewRoleWriter()
	refreshReader := datastore.NewRefreshTokenReader()
	refreshWriter := datastore.NewRefreshTokenWriter()
	authUsecase := usecase.NewAuthUsecase(
		cfg, txManager,
		userReader, userWriter,
		orgReader, orgWriter,
		roleReader, roleWriter,
		refreshReader, refreshWriter,
	)
	authHandler := grpchandler.NewAuthHandler(cfg, logger, authUsecase)

	return &App{
		Logger:      logger,
		Server:      server,
		AuthHandler: authHandler,
		DB:          db,
		Config:      cfg,
	}, nil
}
