// Code generated by MockGen. DO NOT EDIT.
// Source: auth_usecase.go
//
// Generated by this command:
//
//	mockgen -source=auth_usecase.go -destination=mock/mock_auth_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	usecase "github.com/genpick/genpos-mono/backend/internal/usecase"
	input "github.com/genpick/genpos-mono/backend/internal/usecase/input"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthUsecase is a mock of AuthUsecase interface.
type MockAuthUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUsecaseMockRecorder
	isgomock struct{}
}

// MockAuthUsecaseMockRecorder is the mock recorder for MockAuthUsecase.
type MockAuthUsecaseMockRecorder struct {
	mock *MockAuthUsecase
}

// NewMockAuthUsecase creates a new mock instance.
func NewMockAuthUsecase(ctrl *gomock.Controller) *MockAuthUsecase {
	mock := &MockAuthUsecase{ctrl: ctrl}
	mock.recorder = &MockAuthUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUsecase) EXPECT() *MockAuthUsecaseMockRecorder {
	return m.recorder
}

// Me mocks base method.
func (m *MockAuthUsecase) Me(ctx context.Context, userID string) (*entity.User, *entity.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx, userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(*entity.Org)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Me indicates an expected call of Me.
func (mr *MockAuthUsecaseMockRecorder) Me(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockAuthUsecase)(nil).Me), ctx, userID)
}

// Refresh mocks base method.
func (m *MockAuthUsecase) Refresh(ctx context.Context, in input.RefreshInput) (*usecase.AuthSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, in)
	ret0, _ := ret[0].(*usecase.AuthSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthUsecaseMockRecorder) Refresh(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthUsecase)(nil).Refresh), ctx, in)
}

// SignIn mocks base method.
func (m *MockAuthUsecase) SignIn(ctx context.Context, in input.SignInInput) (*usecase.AuthSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, in)
	ret0, _ := ret[0].(*usecase.AuthSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAuthUsecaseMockRecorder) SignIn(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAuthUsecase)(nil).SignIn), ctx, in)
}

// SignOut mocks base method.
func (m *MockAuthUsecase) SignOut(ctx context.Context, in input.SignOutInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignOut", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignOut indicates an expected call of SignOut.
func (mr *MockAuthUsecaseMockRecorder) SignOut(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOut", reflect.TypeOf((*MockAuthUsecase)(nil).SignOut), ctx, in)
}

// SignUp mocks base method.
func (m *MockAuthUsecase) SignUp(ctx context.Context, in input.SignUpInput) (*usecase.AuthSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, in)
	ret0, _ := ret[0].(*usecase.AuthSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockAuthUsecaseMockRecorder) SignUp(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockAuthUsecase)(nil).SignUp), ctx, in)
}
