// Code generated by MockGen. DO NOT EDIT.
// Source: refresh_token_gateway.go
//
// Generated by this command:
//
//	mockgen -source=refresh_token_gateway.go -destination=mock/mock_refresh_token_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshTokenReader is a mock of RefreshTokenReader interface.
type MockRefreshTokenReader struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenReaderMockRecorder
	isgomock struct{}
}

// MockRefreshTokenReaderMockRecorder is the mock recorder for MockRefreshTokenReader.
type MockRefreshTokenReaderMockRecorder struct {
	mock *MockRefreshTokenReader
}

// NewMockRefreshTokenReader creates a new mock instance.
func NewMockRefreshTokenReader(ctrl *gomock.Controller) *MockRefreshTokenReader {
	mock := &MockRefreshTokenReader{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenReader) EXPECT() *MockRefreshTokenReaderMockRecorder {
	return m.recorder
}

// GetByHash mocks base method.
func (m *MockRefreshTokenReader) GetByHash(ctx context.Context, tokenHash string) (*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockRefreshTokenReaderMockRecorder) GetByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockRefreshTokenReader)(nil).GetByHash), ctx, tokenHash)
}

// MockRefreshTokenWriter is a mock of RefreshTokenWriter interface.
type MockRefreshTokenWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenWriterMockRecorder
	isgomock struct{}
}

// MockRefreshTokenWriterMockRecorder is the mock recorder for MockRefreshTokenWriter.
type MockRefreshTokenWriterMockRecorder struct {
	mock *MockRefreshTokenWriter
}

// NewMockRefreshTokenWriter creates a new mock instance.
func NewMockRefreshTokenWriter(ctrl *gomock.Controller) *MockRefreshTokenWriter {
	mock := &MockRefreshTokenWriter{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenWriter) EXPECT() *MockRefreshTokenWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRefreshTokenWriter) Create(ctx context.Context, params gateway.CreateRefreshTokenParams) (*entity.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRefreshTokenWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRefreshTokenWriter)(nil).Create), ctx, params)
}

// Revoke mocks base method.
func (m *MockRefreshTokenWriter) Revoke(ctx context.Context, id string, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockRefreshTokenWriterMockRecorder) Revoke(ctx, id, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockRefreshTokenWriter)(nil).Revoke), ctx, id, revokedAt)
}
