// Code generated by MockGen. DO NOT EDIT.
// Source: org_gateway.go
//
// Generated by this command:
//
//	mockgen -source=org_gateway.go -destination=mock/mock_org_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockOrgReader is a mock of OrgReader interface.
type MockOrgReader struct {
	ctrl     *gomock.Controller
	recorder *MockOrgReaderMockRecorder
	isgomock struct{}
}

// MockOrgReaderMockRecorder is the mock recorder for MockOrgReader.
type MockOrgReaderMockRecorder struct {
	mock *MockOrgReader
}

// NewMockOrgReader creates a new mock instance.
func NewMockOrgReader(ctrl *gomock.Controller) *MockOrgReader {
	mock := &MockOrgReader{ctrl: ctrl}
	mock.recorder = &MockOrgReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgReader) EXPECT() *MockOrgReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockOrgReader) GetByID(ctx context.Context, id string) (*entity.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrgReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrgReader)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockOrgReader) GetBySlug(ctx context.Context, slug string) (*entity.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(*entity.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockOrgReaderMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockOrgReader)(nil).GetBySlug), ctx, slug)
}

// MockOrgWriter is a mock of OrgWriter interface.
type MockOrgWriter struct {
	ctrl     *gomock.Controller
	recorder *MockOrgWriterMockRecorder
	isgomock struct{}
}

// MockOrgWriterMockRecorder is the mock recorder for MockOrgWriter.
type MockOrgWriterMockRecorder struct {
	mock *MockOrgWriter
}

// NewMockOrgWriter creates a new mock instance.
func NewMockOrgWriter(ctrl *gomock.Controller) *MockOrgWriter {
	mock := &MockOrgWriter{ctrl: ctrl}
	mock.recorder = &MockOrgWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrgWriter) EXPECT() *MockOrgWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrgWriter) Create(ctx context.Context, params gateway.CreateOrgParams) (*entity.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrgWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrgWriter)(nil).Create), ctx, params)
}
