// Code generated by MockGen. DO NOT EDIT.
// Source: payment_method_gateway.go
//
// Generated by this command:
//
//	mockgen -source=payment_method_gateway.go -destination=mock/mock_payment_method_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentMethodReader is a mock of PaymentMethodReader interface.
type MockPaymentMethodReader struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMethodReaderMockRecorder
	isgomock struct{}
}

// MockPaymentMethodReaderMockRecorder is the mock recorder for MockPaymentMethodReader.
type MockPaymentMethodReaderMockRecorder struct {
	mock *MockPaymentMethodReader
}

// NewMockPaymentMethodReader creates a new mock instance.
func NewMockPaymentMethodReader(ctrl *gomock.Controller) *MockPaymentMethodReader {
	mock := &MockPaymentMethodReader{ctrl: ctrl}
	mock.recorder = &MockPaymentMethodReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentMethodReader) EXPECT() *MockPaymentMethodReaderMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockPaymentMethodReader) List(ctx context.Context) ([]*entity.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPaymentMethodReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPaymentMethodReader)(nil).List), ctx)
}

// MockPaymentMethodWriter is a mock of PaymentMethodWriter interface.
type MockPaymentMethodWriter struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentMethodWriterMockRecorder
	isgomock struct{}
}

// MockPaymentMethodWriterMockRecorder is the mock recorder for MockPaymentMethodWriter.
type MockPaymentMethodWriterMockRecorder struct {
	mock *MockPaymentMethodWriter
}

// NewMockPaymentMethodWriter creates a new mock instance.
func NewMockPaymentMethodWriter(ctrl *gomock.Controller) *MockPaymentMethodWriter {
	mock := &MockPaymentMethodWriter{ctrl: ctrl}
	mock.recorder = &MockPaymentMethodWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentMethodWriter) EXPECT() *MockPaymentMethodWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPaymentMethodWriter) Create(ctx context.Context, params gateway.CreatePaymentMethodParams) (*entity.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentMethodWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentMethodWriter)(nil).Create), ctx, params)
}

// SoftDelete mocks base method.
func (m *MockPaymentMethodWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockPaymentMethodWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockPaymentMethodWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockPaymentMethodWriter) Update(ctx context.Context, params gateway.UpdatePaymentMethodParams) (*entity.PaymentMethod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.PaymentMethod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPaymentMethodWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPaymentMethodWriter)(nil).Update), ctx, params)
}
