// Code generated by MockGen. DO NOT EDIT.
// Source: purchase_order_gateway.go
//
// Generated by this command:
//
//	mockgen -source=purchase_order_gateway.go -destination=mock/mock_purchase_order_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockPurchaseOrderReader is a mock of PurchaseOrderReader interface.
type MockPurchaseOrderReader struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseOrderReaderMockRecorder
	isgomock struct{}
}

// MockPurchaseOrderReaderMockRecorder is the mock recorder for MockPurchaseOrderReader.
type MockPurchaseOrderReaderMockRecorder struct {
	mock *MockPurchaseOrderReader
}

// NewMockPurchaseOrderReader creates a new mock instance.
func NewMockPurchaseOrderReader(ctrl *gomock.Controller) *MockPurchaseOrderReader {
	mock := &MockPurchaseOrderReader{ctrl: ctrl}
	mock.recorder = &MockPurchaseOrderReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseOrderReader) EXPECT() *MockPurchaseOrderReaderMockRecorder {
	return m.recorder
}

// CountForPrefix mocks base method.
func (m *MockPurchaseOrderReader) CountForPrefix(ctx context.Context, orgID, prefix string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountForPrefix", ctx, orgID, prefix)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountForPrefix indicates an expected call of CountForPrefix.
func (mr *MockPurchaseOrderReaderMockRecorder) CountForPrefix(ctx, orgID, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountForPrefix", reflect.TypeOf((*MockPurchaseOrderReader)(nil).CountForPrefix), ctx, orgID, prefix)
}

// GetByID mocks base method.
func (m *MockPurchaseOrderReader) GetByID(ctx context.Context, id string) (*entity.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPurchaseOrderReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPurchaseOrderReader)(nil).GetByID), ctx, id)
}

// GetItemByID mocks base method.
func (m *MockPurchaseOrderReader) GetItemByID(ctx context.Context, id string) (*entity.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByID", ctx, id)
	ret0, _ := ret[0].(*entity.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByID indicates an expected call of GetItemByID.
func (mr *MockPurchaseOrderReaderMockRecorder) GetItemByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByID", reflect.TypeOf((*MockPurchaseOrderReader)(nil).GetItemByID), ctx, id)
}

// ListItems mocks base method.
func (m *MockPurchaseOrderReader) ListItems(ctx context.Context, poID string) ([]*entity.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, poID)
	ret0, _ := ret[0].([]*entity.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockPurchaseOrderReaderMockRecorder) ListItems(ctx, poID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockPurchaseOrderReader)(nil).ListItems), ctx, poID)
}

// ListStoreRefs mocks base method.
func (m *MockPurchaseOrderReader) ListStoreRefs(ctx context.Context) ([]*entity.StoreRef, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreRefs", ctx)
	ret0, _ := ret[0].([]*entity.StoreRef)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreRefs indicates an expected call of ListStoreRefs.
func (mr *MockPurchaseOrderReaderMockRecorder) ListStoreRefs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreRefs", reflect.TypeOf((*MockPurchaseOrderReader)(nil).ListStoreRefs), ctx)
}

// ListSummaries mocks base method.
func (m *MockPurchaseOrderReader) ListSummaries(ctx context.Context) ([]*entity.PurchaseOrderListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummaries", ctx)
	ret0, _ := ret[0].([]*entity.PurchaseOrderListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummaries indicates an expected call of ListSummaries.
func (mr *MockPurchaseOrderReaderMockRecorder) ListSummaries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummaries", reflect.TypeOf((*MockPurchaseOrderReader)(nil).ListSummaries), ctx)
}

// ListVariantPickerItems mocks base method.
func (m *MockPurchaseOrderReader) ListVariantPickerItems(ctx context.Context) ([]*entity.VariantPickerItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVariantPickerItems", ctx)
	ret0, _ := ret[0].([]*entity.VariantPickerItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVariantPickerItems indicates an expected call of ListVariantPickerItems.
func (mr *MockPurchaseOrderReaderMockRecorder) ListVariantPickerItems(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVariantPickerItems", reflect.TypeOf((*MockPurchaseOrderReader)(nil).ListVariantPickerItems), ctx)
}

// MockPurchaseOrderWriter is a mock of PurchaseOrderWriter interface.
type MockPurchaseOrderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseOrderWriterMockRecorder
	isgomock struct{}
}

// MockPurchaseOrderWriterMockRecorder is the mock recorder for MockPurchaseOrderWriter.
type MockPurchaseOrderWriterMockRecorder struct {
	mock *MockPurchaseOrderWriter
}

// NewMockPurchaseOrderWriter creates a new mock instance.
func NewMockPurchaseOrderWriter(ctrl *gomock.Controller) *MockPurchaseOrderWriter {
	mock := &MockPurchaseOrderWriter{ctrl: ctrl}
	mock.recorder = &MockPurchaseOrderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseOrderWriter) EXPECT() *MockPurchaseOrderWriterMockRecorder {
	return m.recorder
}

// AddItemReceived mocks base method.
func (m *MockPurchaseOrderWriter) AddItemReceived(ctx context.Context, itemID, delta string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItemReceived", ctx, itemID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItemReceived indicates an expected call of AddItemReceived.
func (mr *MockPurchaseOrderWriterMockRecorder) AddItemReceived(ctx, itemID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItemReceived", reflect.TypeOf((*MockPurchaseOrderWriter)(nil).AddItemReceived), ctx, itemID, delta)
}

// Create mocks base method.
func (m *MockPurchaseOrderWriter) Create(ctx context.Context, params gateway.CreatePurchaseOrderParams) (*entity.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPurchaseOrderWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPurchaseOrderWriter)(nil).Create), ctx, params)
}

// DeleteItemsByPO mocks base method.
func (m *MockPurchaseOrderWriter) DeleteItemsByPO(ctx context.Context, poID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItemsByPO", ctx, poID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItemsByPO indicates an expected call of DeleteItemsByPO.
func (mr *MockPurchaseOrderWriterMockRecorder) DeleteItemsByPO(ctx, poID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItemsByPO", reflect.TypeOf((*MockPurchaseOrderWriter)(nil).DeleteItemsByPO), ctx, poID)
}

// InsertItem mocks base method.
func (m *MockPurchaseOrderWriter) InsertItem(ctx context.Context, params gateway.CreatePurchaseOrderItemParams) (*entity.PurchaseOrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertItem", ctx, params)
	ret0, _ := ret[0].(*entity.PurchaseOrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertItem indicates an expected call of InsertItem.
func (mr *MockPurchaseOrderWriterMockRecorder) InsertItem(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertItem", reflect.TypeOf((*MockPurchaseOrderWriter)(nil).InsertItem), ctx, params)
}

// SoftDelete mocks base method.
func (m *MockPurchaseOrderWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockPurchaseOrderWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockPurchaseOrderWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockPurchaseOrderWriter) Update(ctx context.Context, params gateway.UpdatePurchaseOrderParams) (*entity.PurchaseOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.PurchaseOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPurchaseOrderWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPurchaseOrderWriter)(nil).Update), ctx, params)
}

// UpdateStatus mocks base method.
func (m *MockPurchaseOrderWriter) UpdateStatus(ctx context.Context, id, status string, receivedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, receivedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPurchaseOrderWriterMockRecorder) UpdateStatus(ctx, id, status, receivedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPurchaseOrderWriter)(nil).UpdateStatus), ctx, id, status, receivedAt)
}

// MockStockMovementWriter is a mock of StockMovementWriter interface.
type MockStockMovementWriter struct {
	ctrl     *gomock.Controller
	recorder *MockStockMovementWriterMockRecorder
	isgomock struct{}
}

// MockStockMovementWriterMockRecorder is the mock recorder for MockStockMovementWriter.
type MockStockMovementWriterMockRecorder struct {
	mock *MockStockMovementWriter
}

// NewMockStockMovementWriter creates a new mock instance.
func NewMockStockMovementWriter(ctrl *gomock.Controller) *MockStockMovementWriter {
	mock := &MockStockMovementWriter{ctrl: ctrl}
	mock.recorder = &MockStockMovementWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockMovementWriter) EXPECT() *MockStockMovementWriterMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockStockMovementWriter) Insert(ctx context.Context, params gateway.CreateStockMovementParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockStockMovementWriterMockRecorder) Insert(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockStockMovementWriter)(nil).Insert), ctx, params)
}
