// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gateway/product_gateway.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gateway/product_gateway.go -destination=internal/domain/gateway/mock/mock_product_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockProductReader is a mock of ProductReader interface.
type MockProductReader struct {
	ctrl     *gomock.Controller
	recorder *MockProductReaderMockRecorder
	isgomock struct{}
}

// MockProductReaderMockRecorder is the mock recorder for MockProductReader.
type MockProductReaderMockRecorder struct {
	mock *MockProductReader
}

// NewMockProductReader creates a new mock instance.
func NewMockProductReader(ctrl *gomock.Controller) *MockProductReader {
	mock := &MockProductReader{ctrl: ctrl}
	mock.recorder = &MockProductReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductReader) EXPECT() *MockProductReaderMockRecorder {
	return m.recorder
}

// ListProducts mocks base method.
func (m *MockProductReader) ListProducts(ctx context.Context, params gateway.ListProductsParams) ([]*entity.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, params)
	ret0, _ := ret[0].([]*entity.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockProductReaderMockRecorder) ListProducts(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockProductReader)(nil).ListProducts), ctx, params)
}
