// Code generated by MockGen. DO NOT EDIT.
// Source: role_gateway.go
//
// Generated by this command:
//
//	mockgen -source=role_gateway.go -destination=mock/mock_role_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleReader is a mock of RoleReader interface.
type MockRoleReader struct {
	ctrl     *gomock.Controller
	recorder *MockRoleReaderMockRecorder
	isgomock struct{}
}

// MockRoleReaderMockRecorder is the mock recorder for MockRoleReader.
type MockRoleReaderMockRecorder struct {
	mock *MockRoleReader
}

// NewMockRoleReader creates a new mock instance.
func NewMockRoleReader(ctrl *gomock.Controller) *MockRoleReader {
	mock := &MockRoleReader{ctrl: ctrl}
	mock.recorder = &MockRoleReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleReader) EXPECT() *MockRoleReaderMockRecorder {
	return m.recorder
}

// GetByOrgAndName mocks base method.
func (m *MockRoleReader) GetByOrgAndName(ctx context.Context, orgID, name string) (*entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgAndName", ctx, orgID, name)
	ret0, _ := ret[0].(*entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrgAndName indicates an expected call of GetByOrgAndName.
func (mr *MockRoleReaderMockRecorder) GetByOrgAndName(ctx, orgID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgAndName", reflect.TypeOf((*MockRoleReader)(nil).GetByOrgAndName), ctx, orgID, name)
}

// MockRoleWriter is a mock of RoleWriter interface.
type MockRoleWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRoleWriterMockRecorder
	isgomock struct{}
}

// MockRoleWriterMockRecorder is the mock recorder for MockRoleWriter.
type MockRoleWriterMockRecorder struct {
	mock *MockRoleWriter
}

// NewMockRoleWriter creates a new mock instance.
func NewMockRoleWriter(ctrl *gomock.Controller) *MockRoleWriter {
	mock := &MockRoleWriter{ctrl: ctrl}
	mock.recorder = &MockRoleWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleWriter) EXPECT() *MockRoleWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoleWriter) Create(ctx context.Context, params gateway.CreateRoleParams) (*entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoleWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleWriter)(nil).Create), ctx, params)
}
