// Code generated by MockGen. DO NOT EDIT.
// Source: stock_take_gateway.go
//
// Generated by this command:
//
//	mockgen -source=stock_take_gateway.go -destination=mock/mock_stock_take_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockStockTakeReader is a mock of StockTakeReader interface.
type MockStockTakeReader struct {
	ctrl     *gomock.Controller
	recorder *MockStockTakeReaderMockRecorder
	isgomock struct{}
}

// MockStockTakeReaderMockRecorder is the mock recorder for MockStockTakeReader.
type MockStockTakeReaderMockRecorder struct {
	mock *MockStockTakeReader
}

// NewMockStockTakeReader creates a new mock instance.
func NewMockStockTakeReader(ctrl *gomock.Controller) *MockStockTakeReader {
	mock := &MockStockTakeReader{ctrl: ctrl}
	mock.recorder = &MockStockTakeReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockTakeReader) EXPECT() *MockStockTakeReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockStockTakeReader) GetByID(ctx context.Context, id string) (*entity.StockTake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.StockTake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStockTakeReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStockTakeReader)(nil).GetByID), ctx, id)
}

// ListItems mocks base method.
func (m *MockStockTakeReader) ListItems(ctx context.Context, stockTakeID string) ([]*entity.StockTakeItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, stockTakeID)
	ret0, _ := ret[0].([]*entity.StockTakeItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockStockTakeReaderMockRecorder) ListItems(ctx, stockTakeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockStockTakeReader)(nil).ListItems), ctx, stockTakeID)
}

// ListSummaries mocks base method.
func (m *MockStockTakeReader) ListSummaries(ctx context.Context) ([]*entity.StockTakeListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummaries", ctx)
	ret0, _ := ret[0].([]*entity.StockTakeListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummaries indicates an expected call of ListSummaries.
func (mr *MockStockTakeReaderMockRecorder) ListSummaries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummaries", reflect.TypeOf((*MockStockTakeReader)(nil).ListSummaries), ctx)
}

// MockStockTakeWriter is a mock of StockTakeWriter interface.
type MockStockTakeWriter struct {
	ctrl     *gomock.Controller
	recorder *MockStockTakeWriterMockRecorder
	isgomock struct{}
}

// MockStockTakeWriterMockRecorder is the mock recorder for MockStockTakeWriter.
type MockStockTakeWriterMockRecorder struct {
	mock *MockStockTakeWriter
}

// NewMockStockTakeWriter creates a new mock instance.
func NewMockStockTakeWriter(ctrl *gomock.Controller) *MockStockTakeWriter {
	mock := &MockStockTakeWriter{ctrl: ctrl}
	mock.recorder = &MockStockTakeWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockTakeWriter) EXPECT() *MockStockTakeWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStockTakeWriter) Create(ctx context.Context, params gateway.CreateStockTakeParams) (*entity.StockTake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.StockTake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStockTakeWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStockTakeWriter)(nil).Create), ctx, params)
}

// InsertItem mocks base method.
func (m *MockStockTakeWriter) InsertItem(ctx context.Context, params gateway.CreateStockTakeItemParams) (*entity.StockTakeItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertItem", ctx, params)
	ret0, _ := ret[0].(*entity.StockTakeItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertItem indicates an expected call of InsertItem.
func (mr *MockStockTakeWriterMockRecorder) InsertItem(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertItem", reflect.TypeOf((*MockStockTakeWriter)(nil).InsertItem), ctx, params)
}

// SeedItemsFromOnHand mocks base method.
func (m *MockStockTakeWriter) SeedItemsFromOnHand(ctx context.Context, orgID, stockTakeID, storeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeedItemsFromOnHand", ctx, orgID, stockTakeID, storeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SeedItemsFromOnHand indicates an expected call of SeedItemsFromOnHand.
func (mr *MockStockTakeWriterMockRecorder) SeedItemsFromOnHand(ctx, orgID, stockTakeID, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeedItemsFromOnHand", reflect.TypeOf((*MockStockTakeWriter)(nil).SeedItemsFromOnHand), ctx, orgID, stockTakeID, storeID)
}

// SoftDelete mocks base method.
func (m *MockStockTakeWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockStockTakeWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockStockTakeWriter)(nil).SoftDelete), ctx, id)
}

// UpdateItemCount mocks base method.
func (m *MockStockTakeWriter) UpdateItemCount(ctx context.Context, itemID, countedQty string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemCount", ctx, itemID, countedQty)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemCount indicates an expected call of UpdateItemCount.
func (mr *MockStockTakeWriterMockRecorder) UpdateItemCount(ctx, itemID, countedQty any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemCount", reflect.TypeOf((*MockStockTakeWriter)(nil).UpdateItemCount), ctx, itemID, countedQty)
}

// UpdateNotes mocks base method.
func (m *MockStockTakeWriter) UpdateNotes(ctx context.Context, id, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotes", ctx, id, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotes indicates an expected call of UpdateNotes.
func (mr *MockStockTakeWriterMockRecorder) UpdateNotes(ctx, id, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotes", reflect.TypeOf((*MockStockTakeWriter)(nil).UpdateNotes), ctx, id, notes)
}

// UpdateStatus mocks base method.
func (m *MockStockTakeWriter) UpdateStatus(ctx context.Context, id, status string, completedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, completedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockStockTakeWriterMockRecorder) UpdateStatus(ctx, id, status, completedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockStockTakeWriter)(nil).UpdateStatus), ctx, id, status, completedAt)
}
