// Code generated by MockGen. DO NOT EDIT.
// Source: catalog_gateway.go
//
// Generated by this command:
//
//	mockgen -source=catalog_gateway.go -destination=mock/mock_catalog_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryReader is a mock of CategoryReader interface.
type MockCategoryReader struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryReaderMockRecorder
	isgomock struct{}
}

// MockCategoryReaderMockRecorder is the mock recorder for MockCategoryReader.
type MockCategoryReaderMockRecorder struct {
	mock *MockCategoryReader
}

// NewMockCategoryReader creates a new mock instance.
func NewMockCategoryReader(ctrl *gomock.Controller) *MockCategoryReader {
	mock := &MockCategoryReader{ctrl: ctrl}
	mock.recorder = &MockCategoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryReader) EXPECT() *MockCategoryReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockCategoryReader) GetByID(ctx context.Context, id string) (*entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCategoryReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCategoryReader)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockCategoryReader) GetByName(ctx context.Context, name string) (*entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCategoryReaderMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCategoryReader)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockCategoryReader) List(ctx context.Context) ([]*entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCategoryReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCategoryReader)(nil).List), ctx)
}

// MockCategoryWriter is a mock of CategoryWriter interface.
type MockCategoryWriter struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryWriterMockRecorder
	isgomock struct{}
}

// MockCategoryWriterMockRecorder is the mock recorder for MockCategoryWriter.
type MockCategoryWriterMockRecorder struct {
	mock *MockCategoryWriter
}

// NewMockCategoryWriter creates a new mock instance.
func NewMockCategoryWriter(ctrl *gomock.Controller) *MockCategoryWriter {
	mock := &MockCategoryWriter{ctrl: ctrl}
	mock.recorder = &MockCategoryWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryWriter) EXPECT() *MockCategoryWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoryWriter) Create(ctx context.Context, params gateway.CreateCategoryParams) (*entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCategoryWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryWriter)(nil).Create), ctx, params)
}

// SoftDelete mocks base method.
func (m *MockCategoryWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockCategoryWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockCategoryWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockCategoryWriter) Update(ctx context.Context, params gateway.UpdateCategoryParams) (*entity.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCategoryWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryWriter)(nil).Update), ctx, params)
}

// MockProductWriter is a mock of ProductWriter interface.
type MockProductWriter struct {
	ctrl     *gomock.Controller
	recorder *MockProductWriterMockRecorder
	isgomock struct{}
}

// MockProductWriterMockRecorder is the mock recorder for MockProductWriter.
type MockProductWriterMockRecorder struct {
	mock *MockProductWriter
}

// NewMockProductWriter creates a new mock instance.
func NewMockProductWriter(ctrl *gomock.Controller) *MockProductWriter {
	mock := &MockProductWriter{ctrl: ctrl}
	mock.recorder = &MockProductWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductWriter) EXPECT() *MockProductWriterMockRecorder {
	return m.recorder
}

// CreateBase mocks base method.
func (m *MockProductWriter) CreateBase(ctx context.Context, params gateway.CreateProductBaseParams) (*entity.ProductDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBase", ctx, params)
	ret0, _ := ret[0].(*entity.ProductDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBase indicates an expected call of CreateBase.
func (mr *MockProductWriterMockRecorder) CreateBase(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBase", reflect.TypeOf((*MockProductWriter)(nil).CreateBase), ctx, params)
}

// DeleteImagesByProduct mocks base method.
func (m *MockProductWriter) DeleteImagesByProduct(ctx context.Context, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImagesByProduct", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImagesByProduct indicates an expected call of DeleteImagesByProduct.
func (mr *MockProductWriterMockRecorder) DeleteImagesByProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImagesByProduct", reflect.TypeOf((*MockProductWriter)(nil).DeleteImagesByProduct), ctx, productID)
}

// DeleteOptionsByProduct mocks base method.
func (m *MockProductWriter) DeleteOptionsByProduct(ctx context.Context, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOptionsByProduct", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOptionsByProduct indicates an expected call of DeleteOptionsByProduct.
func (mr *MockProductWriterMockRecorder) DeleteOptionsByProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOptionsByProduct", reflect.TypeOf((*MockProductWriter)(nil).DeleteOptionsByProduct), ctx, productID)
}

// InsertImage mocks base method.
func (m *MockProductWriter) InsertImage(ctx context.Context, params gateway.CreateProductImageParams) (*entity.ProductImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertImage", ctx, params)
	ret0, _ := ret[0].(*entity.ProductImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertImage indicates an expected call of InsertImage.
func (mr *MockProductWriterMockRecorder) InsertImage(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertImage", reflect.TypeOf((*MockProductWriter)(nil).InsertImage), ctx, params)
}

// InsertOption mocks base method.
func (m *MockProductWriter) InsertOption(ctx context.Context, params gateway.CreateProductOptionParams) (*entity.ProductOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOption", ctx, params)
	ret0, _ := ret[0].(*entity.ProductOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOption indicates an expected call of InsertOption.
func (mr *MockProductWriterMockRecorder) InsertOption(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOption", reflect.TypeOf((*MockProductWriter)(nil).InsertOption), ctx, params)
}

// InsertOptionValue mocks base method.
func (m *MockProductWriter) InsertOptionValue(ctx context.Context, params gateway.CreateProductOptionValueParams) (*entity.ProductOptionValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOptionValue", ctx, params)
	ret0, _ := ret[0].(*entity.ProductOptionValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOptionValue indicates an expected call of InsertOptionValue.
func (mr *MockProductWriterMockRecorder) InsertOptionValue(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOptionValue", reflect.TypeOf((*MockProductWriter)(nil).InsertOptionValue), ctx, params)
}

// InsertVariant mocks base method.
func (m *MockProductWriter) InsertVariant(ctx context.Context, params gateway.CreateProductVariantParams) (*entity.ProductVariant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVariant", ctx, params)
	ret0, _ := ret[0].(*entity.ProductVariant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertVariant indicates an expected call of InsertVariant.
func (mr *MockProductWriterMockRecorder) InsertVariant(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVariant", reflect.TypeOf((*MockProductWriter)(nil).InsertVariant), ctx, params)
}

// InsertVariantOptionValue mocks base method.
func (m *MockProductWriter) InsertVariantOptionValue(ctx context.Context, orgID, variantID, optionValueID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVariantOptionValue", ctx, orgID, variantID, optionValueID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertVariantOptionValue indicates an expected call of InsertVariantOptionValue.
func (mr *MockProductWriterMockRecorder) InsertVariantOptionValue(ctx, orgID, variantID, optionValueID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVariantOptionValue", reflect.TypeOf((*MockProductWriter)(nil).InsertVariantOptionValue), ctx, orgID, variantID, optionValueID)
}

// SoftDelete mocks base method.
func (m *MockProductWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockProductWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockProductWriter)(nil).SoftDelete), ctx, id)
}

// SoftDeleteVariantsByProduct mocks base method.
func (m *MockProductWriter) SoftDeleteVariantsByProduct(ctx context.Context, productID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteVariantsByProduct", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteVariantsByProduct indicates an expected call of SoftDeleteVariantsByProduct.
func (mr *MockProductWriterMockRecorder) SoftDeleteVariantsByProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteVariantsByProduct", reflect.TypeOf((*MockProductWriter)(nil).SoftDeleteVariantsByProduct), ctx, productID)
}

// UpdateBase mocks base method.
func (m *MockProductWriter) UpdateBase(ctx context.Context, params gateway.UpdateProductBaseParams) (*entity.ProductDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBase", ctx, params)
	ret0, _ := ret[0].(*entity.ProductDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBase indicates an expected call of UpdateBase.
func (mr *MockProductWriterMockRecorder) UpdateBase(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBase", reflect.TypeOf((*MockProductWriter)(nil).UpdateBase), ctx, params)
}

// MockProductDetailReader is a mock of ProductDetailReader interface.
type MockProductDetailReader struct {
	ctrl     *gomock.Controller
	recorder *MockProductDetailReaderMockRecorder
	isgomock struct{}
}

// MockProductDetailReaderMockRecorder is the mock recorder for MockProductDetailReader.
type MockProductDetailReaderMockRecorder struct {
	mock *MockProductDetailReader
}

// NewMockProductDetailReader creates a new mock instance.
func NewMockProductDetailReader(ctrl *gomock.Controller) *MockProductDetailReader {
	mock := &MockProductDetailReader{ctrl: ctrl}
	mock.recorder = &MockProductDetailReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductDetailReader) EXPECT() *MockProductDetailReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockProductDetailReader) GetByID(ctx context.Context, id string) (*entity.ProductDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.ProductDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductDetailReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductDetailReader)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockProductDetailReader) GetByName(ctx context.Context, name string) (*entity.ProductDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entity.ProductDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockProductDetailReaderMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockProductDetailReader)(nil).GetByName), ctx, name)
}

// ListSummaries mocks base method.
func (m *MockProductDetailReader) ListSummaries(ctx context.Context) ([]*entity.ProductListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummaries", ctx)
	ret0, _ := ret[0].([]*entity.ProductListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummaries indicates an expected call of ListSummaries.
func (mr *MockProductDetailReaderMockRecorder) ListSummaries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummaries", reflect.TypeOf((*MockProductDetailReader)(nil).ListSummaries), ctx)
}
