// Code generated by MockGen. DO NOT EDIT.
// Source: tax_class_gateway.go
//
// Generated by this command:
//
//	mockgen -source=tax_class_gateway.go -destination=mock/mock_tax_class_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockTaxClassReader is a mock of TaxClassReader interface.
type MockTaxClassReader struct {
	ctrl     *gomock.Controller
	recorder *MockTaxClassReaderMockRecorder
	isgomock struct{}
}

// MockTaxClassReaderMockRecorder is the mock recorder for MockTaxClassReader.
type MockTaxClassReaderMockRecorder struct {
	mock *MockTaxClassReader
}

// NewMockTaxClassReader creates a new mock instance.
func NewMockTaxClassReader(ctrl *gomock.Controller) *MockTaxClassReader {
	mock := &MockTaxClassReader{ctrl: ctrl}
	mock.recorder = &MockTaxClassReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxClassReader) EXPECT() *MockTaxClassReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTaxClassReader) Get(ctx context.Context, id string) (*entity.TaxClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.TaxClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaxClassReaderMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaxClassReader)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockTaxClassReader) List(ctx context.Context) ([]*entity.TaxClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.TaxClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaxClassReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaxClassReader)(nil).List), ctx)
}

// MockTaxClassWriter is a mock of TaxClassWriter interface.
type MockTaxClassWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTaxClassWriterMockRecorder
	isgomock struct{}
}

// MockTaxClassWriterMockRecorder is the mock recorder for MockTaxClassWriter.
type MockTaxClassWriterMockRecorder struct {
	mock *MockTaxClassWriter
}

// NewMockTaxClassWriter creates a new mock instance.
func NewMockTaxClassWriter(ctrl *gomock.Controller) *MockTaxClassWriter {
	mock := &MockTaxClassWriter{ctrl: ctrl}
	mock.recorder = &MockTaxClassWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxClassWriter) EXPECT() *MockTaxClassWriterMockRecorder {
	return m.recorder
}

// ClearDefaults mocks base method.
func (m *MockTaxClassWriter) ClearDefaults(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDefaults", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDefaults indicates an expected call of ClearDefaults.
func (mr *MockTaxClassWriterMockRecorder) ClearDefaults(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDefaults", reflect.TypeOf((*MockTaxClassWriter)(nil).ClearDefaults), ctx)
}

// Create mocks base method.
func (m *MockTaxClassWriter) Create(ctx context.Context, params gateway.CreateTaxClassParams) (*entity.TaxClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.TaxClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaxClassWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaxClassWriter)(nil).Create), ctx, params)
}

// ReplaceRates mocks base method.
func (m *MockTaxClassWriter) ReplaceRates(ctx context.Context, orgID, classID string, rates []gateway.TaxClassRateParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceRates", ctx, orgID, classID, rates)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceRates indicates an expected call of ReplaceRates.
func (mr *MockTaxClassWriterMockRecorder) ReplaceRates(ctx, orgID, classID, rates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceRates", reflect.TypeOf((*MockTaxClassWriter)(nil).ReplaceRates), ctx, orgID, classID, rates)
}

// SoftDelete mocks base method.
func (m *MockTaxClassWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockTaxClassWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockTaxClassWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockTaxClassWriter) Update(ctx context.Context, params gateway.UpdateTaxClassParams) (*entity.TaxClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.TaxClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaxClassWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaxClassWriter)(nil).Update), ctx, params)
}
