// Code generated by MockGen. DO NOT EDIT.
// Source: order_gateway.go
//
// Generated by this command:
//
//	mockgen -source=order_gateway.go -destination=mock/mock_order_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderReader is a mock of OrderReader interface.
type MockOrderReader struct {
	ctrl     *gomock.Controller
	recorder *MockOrderReaderMockRecorder
	isgomock struct{}
}

// MockOrderReaderMockRecorder is the mock recorder for MockOrderReader.
type MockOrderReaderMockRecorder struct {
	mock *MockOrderReader
}

// NewMockOrderReader creates a new mock instance.
func NewMockOrderReader(ctrl *gomock.Controller) *MockOrderReader {
	mock := &MockOrderReader{ctrl: ctrl}
	mock.recorder = &MockOrderReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderReader) EXPECT() *MockOrderReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockOrderReader) GetByID(ctx context.Context, id string) (*entity.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrderReader)(nil).GetByID), ctx, id)
}

// ListByDateRange mocks base method.
func (m *MockOrderReader) ListByDateRange(ctx context.Context, params gateway.ListOrdersParams) ([]*entity.OrderSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDateRange", ctx, params)
	ret0, _ := ret[0].([]*entity.OrderSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDateRange indicates an expected call of ListByDateRange.
func (mr *MockOrderReaderMockRecorder) ListByDateRange(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDateRange", reflect.TypeOf((*MockOrderReader)(nil).ListByDateRange), ctx, params)
}

// ListLineItems mocks base method.
func (m *MockOrderReader) ListLineItems(ctx context.Context, orderID string) ([]*entity.OrderLineItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLineItems", ctx, orderID)
	ret0, _ := ret[0].([]*entity.OrderLineItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLineItems indicates an expected call of ListLineItems.
func (mr *MockOrderReaderMockRecorder) ListLineItems(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLineItems", reflect.TypeOf((*MockOrderReader)(nil).ListLineItems), ctx, orderID)
}

// ListPayments mocks base method.
func (m *MockOrderReader) ListPayments(ctx context.Context, orderID string) ([]*entity.OrderPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayments", ctx, orderID)
	ret0, _ := ret[0].([]*entity.OrderPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPayments indicates an expected call of ListPayments.
func (mr *MockOrderReaderMockRecorder) ListPayments(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayments", reflect.TypeOf((*MockOrderReader)(nil).ListPayments), ctx, orderID)
}
