// Code generated by MockGen. DO NOT EDIT.
// Source: store_gateway.go
//
// Generated by this command:
//
//	mockgen -source=store_gateway.go -destination=mock/mock_store_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockStoreReader is a mock of StoreReader interface.
type MockStoreReader struct {
	ctrl     *gomock.Controller
	recorder *MockStoreReaderMockRecorder
	isgomock struct{}
}

// MockStoreReaderMockRecorder is the mock recorder for MockStoreReader.
type MockStoreReaderMockRecorder struct {
	mock *MockStoreReader
}

// NewMockStoreReader creates a new mock instance.
func NewMockStoreReader(ctrl *gomock.Controller) *MockStoreReader {
	mock := &MockStoreReader{ctrl: ctrl}
	mock.recorder = &MockStoreReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreReader) EXPECT() *MockStoreReaderMockRecorder {
	return m.recorder
}

// GetFirstForOrg mocks base method.
func (m *MockStoreReader) GetFirstForOrg(ctx context.Context, orgID string) (*entity.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstForOrg", ctx, orgID)
	ret0, _ := ret[0].(*entity.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstForOrg indicates an expected call of GetFirstForOrg.
func (mr *MockStoreReaderMockRecorder) GetFirstForOrg(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstForOrg", reflect.TypeOf((*MockStoreReader)(nil).GetFirstForOrg), ctx, orgID)
}

// List mocks base method.
func (m *MockStoreReader) List(ctx context.Context) ([]*entity.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStoreReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStoreReader)(nil).List), ctx)
}

// MockStoreWriter is a mock of StoreWriter interface.
type MockStoreWriter struct {
	ctrl     *gomock.Controller
	recorder *MockStoreWriterMockRecorder
	isgomock struct{}
}

// MockStoreWriterMockRecorder is the mock recorder for MockStoreWriter.
type MockStoreWriterMockRecorder struct {
	mock *MockStoreWriter
}

// NewMockStoreWriter creates a new mock instance.
func NewMockStoreWriter(ctrl *gomock.Controller) *MockStoreWriter {
	mock := &MockStoreWriter{ctrl: ctrl}
	mock.recorder = &MockStoreWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreWriter) EXPECT() *MockStoreWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStoreWriter) Create(ctx context.Context, params gateway.CreateStoreParams) (*entity.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStoreWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStoreWriter)(nil).Create), ctx, params)
}

// SoftDelete mocks base method.
func (m *MockStoreWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockStoreWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockStoreWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockStoreWriter) Update(ctx context.Context, params gateway.UpdateStoreParams) (*entity.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockStoreWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStoreWriter)(nil).Update), ctx, params)
}
