// Code generated by MockGen. DO NOT EDIT.
// Source: gateway.go
//
// Generated by this command:
//
//	mockgen -source=gateway.go -destination=mock/mock_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTenantDB is a mock of TenantDB interface.
type MockTenantDB struct {
	ctrl     *gomock.Controller
	recorder *MockTenantDBMockRecorder
	isgomock struct{}
}

// MockTenantDBMockRecorder is the mock recorder for MockTenantDB.
type MockTenantDBMockRecorder struct {
	mock *MockTenantDB
}

// NewMockTenantDB creates a new mock instance.
func NewMockTenantDB(ctrl *gomock.Controller) *MockTenantDB {
	mock := &MockTenantDB{ctrl: ctrl}
	mock.recorder = &MockTenantDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantDB) EXPECT() *MockTenantDBMockRecorder {
	return m.recorder
}

// ReadWithTenant mocks base method.
func (m *MockTenantDB) ReadWithTenant(ctx context.Context, orgID string, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadWithTenant", ctx, orgID, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadWithTenant indicates an expected call of ReadWithTenant.
func (mr *MockTenantDBMockRecorder) ReadWithTenant(ctx, orgID, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadWithTenant", reflect.TypeOf((*MockTenantDB)(nil).ReadWithTenant), ctx, orgID, fn)
}

// WithTenant mocks base method.
func (m *MockTenantDB) WithTenant(ctx context.Context, orgID string, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTenant", ctx, orgID, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTenant indicates an expected call of WithTenant.
func (mr *MockTenantDBMockRecorder) WithTenant(ctx, orgID, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTenant", reflect.TypeOf((*MockTenantDB)(nil).WithTenant), ctx, orgID, fn)
}
