// Code generated by MockGen. DO NOT EDIT.
// Source: member_gateway.go
//
// Generated by this command:
//
//	mockgen -source=member_gateway.go -destination=mock/mock_member_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockMemberReader is a mock of MemberReader interface.
type MockMemberReader struct {
	ctrl     *gomock.Controller
	recorder *MockMemberReaderMockRecorder
	isgomock struct{}
}

// MockMemberReaderMockRecorder is the mock recorder for MockMemberReader.
type MockMemberReaderMockRecorder struct {
	mock *MockMemberReader
}

// NewMockMemberReader creates a new mock instance.
func NewMockMemberReader(ctrl *gomock.Controller) *MockMemberReader {
	mock := &MockMemberReader{ctrl: ctrl}
	mock.recorder = &MockMemberReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberReader) EXPECT() *MockMemberReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockMemberReader) GetByID(ctx context.Context, id string) (*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMemberReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMemberReader)(nil).GetByID), ctx, id)
}

// HasStoreAccess mocks base method.
func (m *MockMemberReader) HasStoreAccess(ctx context.Context, userID, storeID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasStoreAccess", ctx, userID, storeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasStoreAccess indicates an expected call of HasStoreAccess.
func (mr *MockMemberReaderMockRecorder) HasStoreAccess(ctx, userID, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasStoreAccess", reflect.TypeOf((*MockMemberReader)(nil).HasStoreAccess), ctx, userID, storeID)
}

// List mocks base method.
func (m *MockMemberReader) List(ctx context.Context) ([]*entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMemberReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMemberReader)(nil).List), ctx)
}

// ListRoleOptions mocks base method.
func (m *MockMemberReader) ListRoleOptions(ctx context.Context, orgID string) ([]*entity.RoleOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoleOptions", ctx, orgID)
	ret0, _ := ret[0].([]*entity.RoleOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoleOptions indicates an expected call of ListRoleOptions.
func (mr *MockMemberReaderMockRecorder) ListRoleOptions(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleOptions", reflect.TypeOf((*MockMemberReader)(nil).ListRoleOptions), ctx, orgID)
}

// MockMemberWriter is a mock of MemberWriter interface.
type MockMemberWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMemberWriterMockRecorder
	isgomock struct{}
}

// MockMemberWriterMockRecorder is the mock recorder for MockMemberWriter.
type MockMemberWriterMockRecorder struct {
	mock *MockMemberWriter
}

// NewMockMemberWriter creates a new mock instance.
func NewMockMemberWriter(ctrl *gomock.Controller) *MockMemberWriter {
	mock := &MockMemberWriter{ctrl: ctrl}
	mock.recorder = &MockMemberWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberWriter) EXPECT() *MockMemberWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMemberWriter) Create(ctx context.Context, params gateway.CreateMemberParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMemberWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMemberWriter)(nil).Create), ctx, params)
}

// ReplaceStores mocks base method.
func (m *MockMemberWriter) ReplaceStores(ctx context.Context, orgID, userID string, storeIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceStores", ctx, orgID, userID, storeIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceStores indicates an expected call of ReplaceStores.
func (mr *MockMemberWriterMockRecorder) ReplaceStores(ctx, orgID, userID, storeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceStores", reflect.TypeOf((*MockMemberWriter)(nil).ReplaceStores), ctx, orgID, userID, storeIDs)
}

// SoftDelete mocks base method.
func (m *MockMemberWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockMemberWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockMemberWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockMemberWriter) Update(ctx context.Context, params gateway.UpdateMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMemberWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMemberWriter)(nil).Update), ctx, params)
}
