// Code generated by MockGen. DO NOT EDIT.
// Source: customer_gateway.go
//
// Generated by this command:
//
//	mockgen -source=customer_gateway.go -destination=mock/mock_customer_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomerReader is a mock of CustomerReader interface.
type MockCustomerReader struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerReaderMockRecorder
	isgomock struct{}
}

// MockCustomerReaderMockRecorder is the mock recorder for MockCustomerReader.
type MockCustomerReaderMockRecorder struct {
	mock *MockCustomerReader
}

// NewMockCustomerReader creates a new mock instance.
func NewMockCustomerReader(ctrl *gomock.Controller) *MockCustomerReader {
	mock := &MockCustomerReader{ctrl: ctrl}
	mock.recorder = &MockCustomerReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerReader) EXPECT() *MockCustomerReaderMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockCustomerReader) GetByEmail(ctx context.Context, email string) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockCustomerReaderMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockCustomerReader)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockCustomerReader) GetByID(ctx context.Context, id string) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCustomerReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCustomerReader)(nil).GetByID), ctx, id)
}

// GetByPhone mocks base method.
func (m *MockCustomerReader) GetByPhone(ctx context.Context, phone string) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhone", ctx, phone)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhone indicates an expected call of GetByPhone.
func (mr *MockCustomerReaderMockRecorder) GetByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhone", reflect.TypeOf((*MockCustomerReader)(nil).GetByPhone), ctx, phone)
}

// ListGroupIDsByCustomer mocks base method.
func (m *MockCustomerReader) ListGroupIDsByCustomer(ctx context.Context, customerID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupIDsByCustomer", ctx, customerID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupIDsByCustomer indicates an expected call of ListGroupIDsByCustomer.
func (mr *MockCustomerReaderMockRecorder) ListGroupIDsByCustomer(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupIDsByCustomer", reflect.TypeOf((*MockCustomerReader)(nil).ListGroupIDsByCustomer), ctx, customerID)
}

// ListSummaries mocks base method.
func (m *MockCustomerReader) ListSummaries(ctx context.Context) ([]*entity.CustomerListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSummaries", ctx)
	ret0, _ := ret[0].([]*entity.CustomerListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSummaries indicates an expected call of ListSummaries.
func (mr *MockCustomerReaderMockRecorder) ListSummaries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSummaries", reflect.TypeOf((*MockCustomerReader)(nil).ListSummaries), ctx)
}

// MockCustomerWriter is a mock of CustomerWriter interface.
type MockCustomerWriter struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerWriterMockRecorder
	isgomock struct{}
}

// MockCustomerWriterMockRecorder is the mock recorder for MockCustomerWriter.
type MockCustomerWriterMockRecorder struct {
	mock *MockCustomerWriter
}

// NewMockCustomerWriter creates a new mock instance.
func NewMockCustomerWriter(ctrl *gomock.Controller) *MockCustomerWriter {
	mock := &MockCustomerWriter{ctrl: ctrl}
	mock.recorder = &MockCustomerWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerWriter) EXPECT() *MockCustomerWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerWriter) Create(ctx context.Context, params gateway.CreateCustomerParams) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerWriter)(nil).Create), ctx, params)
}

// ReplaceGroups mocks base method.
func (m *MockCustomerWriter) ReplaceGroups(ctx context.Context, orgID, customerID string, groupIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceGroups", ctx, orgID, customerID, groupIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceGroups indicates an expected call of ReplaceGroups.
func (mr *MockCustomerWriterMockRecorder) ReplaceGroups(ctx, orgID, customerID, groupIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceGroups", reflect.TypeOf((*MockCustomerWriter)(nil).ReplaceGroups), ctx, orgID, customerID, groupIDs)
}

// SoftDelete mocks base method.
func (m *MockCustomerWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockCustomerWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockCustomerWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockCustomerWriter) Update(ctx context.Context, params gateway.UpdateCustomerParams) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCustomerWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerWriter)(nil).Update), ctx, params)
}

// MockCustomerGroupReader is a mock of CustomerGroupReader interface.
type MockCustomerGroupReader struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerGroupReaderMockRecorder
	isgomock struct{}
}

// MockCustomerGroupReaderMockRecorder is the mock recorder for MockCustomerGroupReader.
type MockCustomerGroupReaderMockRecorder struct {
	mock *MockCustomerGroupReader
}

// NewMockCustomerGroupReader creates a new mock instance.
func NewMockCustomerGroupReader(ctrl *gomock.Controller) *MockCustomerGroupReader {
	mock := &MockCustomerGroupReader{ctrl: ctrl}
	mock.recorder = &MockCustomerGroupReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerGroupReader) EXPECT() *MockCustomerGroupReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockCustomerGroupReader) GetByID(ctx context.Context, id string) (*entity.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCustomerGroupReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCustomerGroupReader)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockCustomerGroupReader) GetByName(ctx context.Context, name string) (*entity.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entity.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockCustomerGroupReaderMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockCustomerGroupReader)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockCustomerGroupReader) List(ctx context.Context) ([]*entity.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCustomerGroupReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCustomerGroupReader)(nil).List), ctx)
}

// MockCustomerGroupWriter is a mock of CustomerGroupWriter interface.
type MockCustomerGroupWriter struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerGroupWriterMockRecorder
	isgomock struct{}
}

// MockCustomerGroupWriterMockRecorder is the mock recorder for MockCustomerGroupWriter.
type MockCustomerGroupWriterMockRecorder struct {
	mock *MockCustomerGroupWriter
}

// NewMockCustomerGroupWriter creates a new mock instance.
func NewMockCustomerGroupWriter(ctrl *gomock.Controller) *MockCustomerGroupWriter {
	mock := &MockCustomerGroupWriter{ctrl: ctrl}
	mock.recorder = &MockCustomerGroupWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerGroupWriter) EXPECT() *MockCustomerGroupWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomerGroupWriter) Create(ctx context.Context, params gateway.CreateCustomerGroupParams) (*entity.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerGroupWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomerGroupWriter)(nil).Create), ctx, params)
}

// SoftDelete mocks base method.
func (m *MockCustomerGroupWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockCustomerGroupWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockCustomerGroupWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockCustomerGroupWriter) Update(ctx context.Context, params gateway.UpdateCustomerGroupParams) (*entity.CustomerGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.CustomerGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCustomerGroupWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerGroupWriter)(nil).Update), ctx, params)
}
