// Code generated by MockGen. DO NOT EDIT.
// Source: tax_rate_gateway.go
//
// Generated by this command:
//
//	mockgen -source=tax_rate_gateway.go -destination=mock/mock_tax_rate_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockTaxRateReader is a mock of TaxRateReader interface.
type MockTaxRateReader struct {
	ctrl     *gomock.Controller
	recorder *MockTaxRateReaderMockRecorder
	isgomock struct{}
}

// MockTaxRateReaderMockRecorder is the mock recorder for MockTaxRateReader.
type MockTaxRateReaderMockRecorder struct {
	mock *MockTaxRateReader
}

// NewMockTaxRateReader creates a new mock instance.
func NewMockTaxRateReader(ctrl *gomock.Controller) *MockTaxRateReader {
	mock := &MockTaxRateReader{ctrl: ctrl}
	mock.recorder = &MockTaxRateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxRateReader) EXPECT() *MockTaxRateReaderMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockTaxRateReader) List(ctx context.Context) ([]*entity.TaxRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.TaxRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaxRateReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaxRateReader)(nil).List), ctx)
}

// MockTaxRateWriter is a mock of TaxRateWriter interface.
type MockTaxRateWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTaxRateWriterMockRecorder
	isgomock struct{}
}

// MockTaxRateWriterMockRecorder is the mock recorder for MockTaxRateWriter.
type MockTaxRateWriterMockRecorder struct {
	mock *MockTaxRateWriter
}

// NewMockTaxRateWriter creates a new mock instance.
func NewMockTaxRateWriter(ctrl *gomock.Controller) *MockTaxRateWriter {
	mock := &MockTaxRateWriter{ctrl: ctrl}
	mock.recorder = &MockTaxRateWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaxRateWriter) EXPECT() *MockTaxRateWriterMockRecorder {
	return m.recorder
}

// ClearDefaults mocks base method.
func (m *MockTaxRateWriter) ClearDefaults(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDefaults", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDefaults indicates an expected call of ClearDefaults.
func (mr *MockTaxRateWriterMockRecorder) ClearDefaults(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDefaults", reflect.TypeOf((*MockTaxRateWriter)(nil).ClearDefaults), ctx)
}

// Create mocks base method.
func (m *MockTaxRateWriter) Create(ctx context.Context, params gateway.CreateTaxRateParams) (*entity.TaxRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.TaxRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaxRateWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaxRateWriter)(nil).Create), ctx, params)
}

// SoftDelete mocks base method.
func (m *MockTaxRateWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockTaxRateWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockTaxRateWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockTaxRateWriter) Update(ctx context.Context, params gateway.UpdateTaxRateParams) (*entity.TaxRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.TaxRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaxRateWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaxRateWriter)(nil).Update), ctx, params)
}
