// Code generated by MockGen. DO NOT EDIT.
// Source: supplier_gateway.go
//
// Generated by this command:
//
//	mockgen -source=supplier_gateway.go -destination=mock/mock_supplier_gateway.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/genpick/genpos-mono/backend/internal/domain/entity"
	gateway "github.com/genpick/genpos-mono/backend/internal/domain/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockSupplierReader is a mock of SupplierReader interface.
type MockSupplierReader struct {
	ctrl     *gomock.Controller
	recorder *MockSupplierReaderMockRecorder
	isgomock struct{}
}

// MockSupplierReaderMockRecorder is the mock recorder for MockSupplierReader.
type MockSupplierReaderMockRecorder struct {
	mock *MockSupplierReader
}

// NewMockSupplierReader creates a new mock instance.
func NewMockSupplierReader(ctrl *gomock.Controller) *MockSupplierReader {
	mock := &MockSupplierReader{ctrl: ctrl}
	mock.recorder = &MockSupplierReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupplierReader) EXPECT() *MockSupplierReaderMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockSupplierReader) GetByID(ctx context.Context, id string) (*entity.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSupplierReaderMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSupplierReader)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockSupplierReader) List(ctx context.Context) ([]*entity.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSupplierReaderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSupplierReader)(nil).List), ctx)
}

// MockSupplierWriter is a mock of SupplierWriter interface.
type MockSupplierWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSupplierWriterMockRecorder
	isgomock struct{}
}

// MockSupplierWriterMockRecorder is the mock recorder for MockSupplierWriter.
type MockSupplierWriterMockRecorder struct {
	mock *MockSupplierWriter
}

// NewMockSupplierWriter creates a new mock instance.
func NewMockSupplierWriter(ctrl *gomock.Controller) *MockSupplierWriter {
	mock := &MockSupplierWriter{ctrl: ctrl}
	mock.recorder = &MockSupplierWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupplierWriter) EXPECT() *MockSupplierWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSupplierWriter) Create(ctx context.Context, params gateway.CreateSupplierParams) (*entity.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(*entity.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSupplierWriterMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSupplierWriter)(nil).Create), ctx, params)
}

// SoftDelete mocks base method.
func (m *MockSupplierWriter) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockSupplierWriterMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockSupplierWriter)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockSupplierWriter) Update(ctx context.Context, params gateway.UpdateSupplierParams) (*entity.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, params)
	ret0, _ := ret[0].(*entity.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSupplierWriterMockRecorder) Update(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSupplierWriter)(nil).Update), ctx, params)
}
